{{- if and .Values.webhooksServer.enabled .Values.rbac.installClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kargo.webhooksServer.fullname" . }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.webhooksServer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
