{{- if .Values.webhooksServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo.webhooksServer.fullname" . }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.webhooksServer.labels" . | nindent 4 }}
{{- end }}
