FROM golang:1.20.7-bookworm

ARG TARGETARCH

ARG BUF_VERSION=v1.15.1
ARG CONTROLLER_GEN_VERSION=v0.11.3
ARG GOLANGCI_LINT_VERSION=1.51.2
ARG HELM_VERSION=v3.10.0
ARG NODE_VERSION=18.x

RUN go install github.com/bufbuild/buf/cmd/buf@${BUF_VERSION} \
    && go install sigs.k8s.io/controller-tools/cmd/controller-gen@${CONTROLLER_GEN_VERSION} \
    && cd /usr/local/bin \
    && curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${TARGETARCH}.tar.gz \
        | tar xvz golangci-lint-${GOLANGCI_LINT_VERSION}-linux-${TARGETARCH}/golangci-lint --strip-components=1 \
    && curl -sSfL https://get.helm.sh/helm-$HELM_VERSION-linux-${TARGETARCH}.tar.gz \
        | tar xvz linux-${TARGETARCH}/helm --strip-components=1 \
    && curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash \
    && apt install nodejs \
    && curl -fsSL https://get.pnpm.io/install.sh | bash \
    && mv /root/.local/share/pnpm/pnpm /usr/bin
