// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package database

import (
	"context"
	"time"
)

const deleteProjectByName = `-- name: DeleteProjectByName :exec
DELETE FROM projects WHERE name = $1
`

func (q *Queries) DeleteProjectByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteProjectByName, name)
	return err
}

const deleteProjectsByID = `-- name: DeleteProjectsByID :exec
DELETE FROM projects WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteProjectsByID(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteProjectsByID, dollar_1)
	return err
}

const deleteReplacedProject = `-- name: DeleteReplacedProject :exec
DELETE FROM projects
WHERE name = $1 AND id <> $2
`

type DeleteReplacedProjectParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

func (q *Queries) DeleteReplacedProject(ctx context.Context, arg DeleteReplacedProjectParams) error {
	_, err := q.db.Exec(ctx, deleteReplacedProject, arg.Name, arg.ID)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, created_at, synced_at FROM projects ORDER BY id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :exec
INSERT INTO projects (id, name, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    created_at = EXCLUDED.created_at,
    synced_at = CURRENT_TIMESTAMP
`

type UpsertProjectParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) error {
	_, err := q.db.Exec(ctx, upsertProject, arg.ID, arg.Name, arg.CreatedAt)
	return err
}
