# Default values for argocd-kit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

  ## All settings relating to the Argo CD control plane this controller will
  ## integrate with.
  argocd:
    ## The namespace into which Argo CD is installed.
    namespace: argocd
    ## Specifies whether Kargo may borrow repository credentials (specially
    ## formatted and specially annotated Secrets) from Argo CD.
    enableCredentialBorrowing: true
