// Package datacenter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package datacenter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for RestMergeStrategyId.
const (
	Ff           RestMergeStrategyId = "ff"
	FfOnly       RestMergeStrategyId = "ff-only"
	NoFf         RestMergeStrategyId = "no-ff"
	RebaseFfOnly RestMergeStrategyId = "rebase-ff-only"
	RebaseNoFf   RestMergeStrategyId = "rebase-no-ff"
	Squash       RestMergeStrategyId = "squash"
	SquashFfOnly RestMergeStrategyId = "squash-ff-only"
)

// Valid indicates whether the value is a known member of the RestMergeStrategyId enum.
func (e RestMergeStrategyId) Valid() bool {
	switch e {
	case Ff:
		return true
	case FfOnly:
		return true
	case NoFf:
		return true
	case RebaseFfOnly:
		return true
	case RebaseNoFf:
		return true
	case Squash:
		return true
	case SquashFfOnly:
		return true
	default:
		return false
	}
}

// Defines values for RestPullRequestState.
const (
	RestPullRequestStateDECLINED RestPullRequestState = "DECLINED"
	RestPullRequestStateMERGED   RestPullRequestState = "MERGED"
	RestPullRequestStateOPEN     RestPullRequestState = "OPEN"
)

// Valid indicates whether the value is a known member of the RestPullRequestState enum.
func (e RestPullRequestState) Valid() bool {
	switch e {
	case RestPullRequestStateDECLINED:
		return true
	case RestPullRequestStateMERGED:
		return true
	case RestPullRequestStateOPEN:
		return true
	default:
		return false
	}
}

// Defines values for GetPullRequestsParamsState.
const (
	GetPullRequestsParamsStateALL      GetPullRequestsParamsState = "ALL"
	GetPullRequestsParamsStateDECLINED GetPullRequestsParamsState = "DECLINED"
	GetPullRequestsParamsStateMERGED   GetPullRequestsParamsState = "MERGED"
	GetPullRequestsParamsStateOPEN     GetPullRequestsParamsState = "OPEN"
)

// Valid indicates whether the value is a known member of the GetPullRequestsParamsState enum.
func (e GetPullRequestsParamsState) Valid() bool {
	switch e {
	case GetPullRequestsParamsStateALL:
		return true
	case GetPullRequestsParamsStateDECLINED:
		return true
	case GetPullRequestsParamsStateMERGED:
		return true
	case GetPullRequestsParamsStateOPEN:
		return true
	default:
		return false
	}
}

// RestBranchDeleteRequest defines model for RestBranchDeleteRequest.
type RestBranchDeleteRequest struct {
	DryRun *bool  `json:"dryRun,omitempty"`
	Name   string `json:"name"`
}

// RestCommit defines model for RestCommit.
type RestCommit struct {
	DisplayId *string `json:"displayId,omitempty"`
	Id        *string `json:"id,omitempty"`
	Message   *string `json:"message,omitempty"`
}

// RestCreateRef defines model for RestCreateRef.
type RestCreateRef struct {
	Id         string            `json:"id"`
	Repository RestRefRepository `json:"repository"`
}

// RestHref defines model for RestHref.
type RestHref struct {
	Href *string `json:"href,omitempty"`
}

// RestMergeConfig defines model for RestMergeConfig.
type RestMergeConfig struct {
	Message  *string            `json:"message,omitempty"`
	Strategy *RestMergeStrategy `json:"strategy,omitempty"`
}

// RestMergeStrategy defines model for RestMergeStrategy.
type RestMergeStrategy struct {
	Id *RestMergeStrategyId `json:"id,omitempty"`
}

// RestMergeStrategyId defines model for RestMergeStrategy.Id.
type RestMergeStrategyId string

// RestProject defines model for RestProject.
type RestProject struct {
	Key *string `json:"key,omitempty"`
}

// RestPullRequest defines model for RestPullRequest.
type RestPullRequest struct {
	Closed      *bool                 `json:"closed,omitempty"`
	CreatedDate *int64                `json:"createdDate,omitempty"`
	Description *string               `json:"description,omitempty"`
	Draft       *bool                 `json:"draft,omitempty"`
	FromRef     *RestRef              `json:"fromRef,omitempty"`
	Id          *int                  `json:"id,omitempty"`
	Links       *RestPullRequestLinks `json:"links,omitempty"`
	Locked      *bool                 `json:"locked,omitempty"`
	Open        *bool                 `json:"open,omitempty"`
	State       *RestPullRequestState `json:"state,omitempty"`
	Title       *string               `json:"title,omitempty"`
	ToRef       *RestRef              `json:"toRef,omitempty"`
	UpdatedDate *int64                `json:"updatedDate,omitempty"`
	Version     *int                  `json:"version,omitempty"`
}

// RestPullRequestState defines model for RestPullRequest.State.
type RestPullRequestState string

// RestPullRequestCreate defines model for RestPullRequestCreate.
type RestPullRequestCreate struct {
	Description *string       `json:"description,omitempty"`
	FromRef     RestCreateRef `json:"fromRef"`
	Title       string        `json:"title"`
	ToRef       RestCreateRef `json:"toRef"`
}

// RestPullRequestLinks defines model for RestPullRequestLinks.
type RestPullRequestLinks struct {
	Self *[]RestHref `json:"self,omitempty"`
}

// RestPullRequestPage defines model for RestPullRequestPage.
type RestPullRequestPage struct {
	IsLastPage    *bool              `json:"isLastPage,omitempty"`
	Limit         *int               `json:"limit,omitempty"`
	NextPageStart *int               `json:"nextPageStart,omitempty"`
	Size          *int               `json:"size,omitempty"`
	Start         *int               `json:"start,omitempty"`
	Values        *[]RestPullRequest `json:"values,omitempty"`
}

// RestRef defines model for RestRef.
type RestRef struct {
	DisplayId    *string            `json:"displayId,omitempty"`
	Id           *string            `json:"id,omitempty"`
	LatestCommit *string            `json:"latestCommit,omitempty"`
	Repository   *RestRefRepository `json:"repository,omitempty"`
}

// RestRefRepository defines model for RestRefRepository.
type RestRefRepository struct {
	Project *RestProject `json:"project,omitempty"`
	Slug    *string      `json:"slug,omitempty"`
}

// GetPullRequestsParams defines parameters for GetPullRequests.
type GetPullRequestsParams struct {
	// State Filter by state. ALL returns pull requests in any state.
	State *GetPullRequestsParamsState `form:"state,omitempty" json:"state,omitempty"`
	Start *int                        `form:"start,omitempty" json:"start,omitempty"`
	Limit *int                        `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetPullRequestsParamsState defines parameters for GetPullRequests.
type GetPullRequestsParamsState string

// MergePullRequestParams defines parameters for MergePullRequest.
type MergePullRequestParams struct {
	// Version The current version of the pull request. Required to prevent merging a stale PR.
	Version int `form:"version" json:"version"`
}

// CreatePullRequestJSONRequestBody defines body for CreatePullRequest for application/json ContentType.
type CreatePullRequestJSONRequestBody = RestPullRequestCreate

// MergePullRequestJSONRequestBody defines body for MergePullRequest for application/json ContentType.
type MergePullRequestJSONRequestBody = RestMergeConfig

// DeleteBranchJSONRequestBody defines body for DeleteBranch for application/json ContentType.
type DeleteBranchJSONRequestBody = RestBranchDeleteRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetCommit request
	GetCommit(ctx context.Context, projectKey string, repositorySlug string, commitId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPullRequests request
	GetPullRequests(ctx context.Context, projectKey string, repositorySlug string, params *GetPullRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePullRequestWithBody request with any body
	CreatePullRequestWithBody(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePullRequest(ctx context.Context, projectKey string, repositorySlug string, body CreatePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPullRequest request
	GetPullRequest(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MergePullRequestWithBody request with any body
	MergePullRequestWithBody(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	MergePullRequest(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, body MergePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteBranchWithBody request with any body
	DeleteBranchWithBody(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteBranch(ctx context.Context, projectKey string, repositorySlug string, body DeleteBranchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetCommit(ctx context.Context, projectKey string, repositorySlug string, commitId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCommitRequest(c.Server, projectKey, repositorySlug, commitId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPullRequests(ctx context.Context, projectKey string, repositorySlug string, params *GetPullRequestsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPullRequestsRequest(c.Server, projectKey, repositorySlug, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePullRequestWithBody(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePullRequestRequestWithBody(c.Server, projectKey, repositorySlug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePullRequest(ctx context.Context, projectKey string, repositorySlug string, body CreatePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePullRequestRequest(c.Server, projectKey, repositorySlug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPullRequest(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPullRequestRequest(c.Server, projectKey, repositorySlug, pullRequestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MergePullRequestWithBody(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMergePullRequestRequestWithBody(c.Server, projectKey, repositorySlug, pullRequestId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MergePullRequest(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, body MergePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMergePullRequestRequest(c.Server, projectKey, repositorySlug, pullRequestId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBranchWithBody(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBranchRequestWithBody(c.Server, projectKey, repositorySlug, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteBranch(ctx context.Context, projectKey string, repositorySlug string, body DeleteBranchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteBranchRequest(c.Server, projectKey, repositorySlug, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetCommitRequest generates requests for GetCommit
func NewGetCommitRequest(server string, projectKey string, repositorySlug string, commitId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "commitId", commitId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/api/1.0/projects/%s/repos/%s/commits/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPullRequestsRequest generates requests for GetPullRequests
func NewGetPullRequestsRequest(server string, projectKey string, repositorySlug string, params *GetPullRequestsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/api/1.0/projects/%s/repos/%s/pull-requests", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Start != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "start", *params.Start, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePullRequestRequest calls the generic CreatePullRequest builder with application/json body
func NewCreatePullRequestRequest(server string, projectKey string, repositorySlug string, body CreatePullRequestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePullRequestRequestWithBody(server, projectKey, repositorySlug, "application/json", bodyReader)
}

// NewCreatePullRequestRequestWithBody generates requests for CreatePullRequest with any type of body
func NewCreatePullRequestRequestWithBody(server string, projectKey string, repositorySlug string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/api/1.0/projects/%s/repos/%s/pull-requests", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPullRequestRequest generates requests for GetPullRequest
func NewGetPullRequestRequest(server string, projectKey string, repositorySlug string, pullRequestId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "pullRequestId", pullRequestId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/api/1.0/projects/%s/repos/%s/pull-requests/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMergePullRequestRequest calls the generic MergePullRequest builder with application/json body
func NewMergePullRequestRequest(server string, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, body MergePullRequestJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewMergePullRequestRequestWithBody(server, projectKey, repositorySlug, pullRequestId, params, "application/json", bodyReader)
}

// NewMergePullRequestRequestWithBody generates requests for MergePullRequest with any type of body
func NewMergePullRequestRequestWithBody(server string, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "pullRequestId", pullRequestId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/api/1.0/projects/%s/repos/%s/pull-requests/%s/merge", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteBranchRequest calls the generic DeleteBranch builder with application/json body
func NewDeleteBranchRequest(server string, projectKey string, repositorySlug string, body DeleteBranchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteBranchRequestWithBody(server, projectKey, repositorySlug, "application/json", bodyReader)
}

// NewDeleteBranchRequestWithBody generates requests for DeleteBranch with any type of body
func NewDeleteBranchRequestWithBody(server string, projectKey string, repositorySlug string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "projectKey", projectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "repositorySlug", repositorySlug, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rest/branch-utils/latest/projects/%s/repos/%s/branches", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetCommitWithResponse request
	GetCommitWithResponse(ctx context.Context, projectKey string, repositorySlug string, commitId string, reqEditors ...RequestEditorFn) (*GetCommitResponse, error)

	// GetPullRequestsWithResponse request
	GetPullRequestsWithResponse(ctx context.Context, projectKey string, repositorySlug string, params *GetPullRequestsParams, reqEditors ...RequestEditorFn) (*GetPullRequestsResponse, error)

	// CreatePullRequestWithBodyWithResponse request with any body
	CreatePullRequestWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePullRequestResponse, error)

	CreatePullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, body CreatePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePullRequestResponse, error)

	// GetPullRequestWithResponse request
	GetPullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, reqEditors ...RequestEditorFn) (*GetPullRequestResponse, error)

	// MergePullRequestWithBodyWithResponse request with any body
	MergePullRequestWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MergePullRequestResponse, error)

	MergePullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, body MergePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*MergePullRequestResponse, error)

	// DeleteBranchWithBodyWithResponse request with any body
	DeleteBranchWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteBranchResponse, error)

	DeleteBranchWithResponse(ctx context.Context, projectKey string, repositorySlug string, body DeleteBranchJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteBranchResponse, error)
}

type GetCommitResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RestCommit
}

// Status returns HTTPResponse.Status
func (r GetCommitResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCommitResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCommitResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPullRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RestPullRequestPage
}

// Status returns HTTPResponse.Status
func (r GetPullRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPullRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPullRequestsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePullRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RestPullRequest
}

// Status returns HTTPResponse.Status
func (r CreatePullRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePullRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePullRequestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPullRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RestPullRequest
}

// Status returns HTTPResponse.Status
func (r GetPullRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPullRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPullRequestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MergePullRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RestPullRequest
}

// Status returns HTTPResponse.Status
func (r MergePullRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MergePullRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MergePullRequestResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteBranchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteBranchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteBranchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteBranchResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetCommitWithResponse request returning *GetCommitResponse
func (c *ClientWithResponses) GetCommitWithResponse(ctx context.Context, projectKey string, repositorySlug string, commitId string, reqEditors ...RequestEditorFn) (*GetCommitResponse, error) {
	rsp, err := c.GetCommit(ctx, projectKey, repositorySlug, commitId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCommitResponse(rsp)
}

// GetPullRequestsWithResponse request returning *GetPullRequestsResponse
func (c *ClientWithResponses) GetPullRequestsWithResponse(ctx context.Context, projectKey string, repositorySlug string, params *GetPullRequestsParams, reqEditors ...RequestEditorFn) (*GetPullRequestsResponse, error) {
	rsp, err := c.GetPullRequests(ctx, projectKey, repositorySlug, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPullRequestsResponse(rsp)
}

// CreatePullRequestWithBodyWithResponse request with arbitrary body returning *CreatePullRequestResponse
func (c *ClientWithResponses) CreatePullRequestWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePullRequestResponse, error) {
	rsp, err := c.CreatePullRequestWithBody(ctx, projectKey, repositorySlug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePullRequestResponse(rsp)
}

func (c *ClientWithResponses) CreatePullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, body CreatePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePullRequestResponse, error) {
	rsp, err := c.CreatePullRequest(ctx, projectKey, repositorySlug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePullRequestResponse(rsp)
}

// GetPullRequestWithResponse request returning *GetPullRequestResponse
func (c *ClientWithResponses) GetPullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, reqEditors ...RequestEditorFn) (*GetPullRequestResponse, error) {
	rsp, err := c.GetPullRequest(ctx, projectKey, repositorySlug, pullRequestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPullRequestResponse(rsp)
}

// MergePullRequestWithBodyWithResponse request with arbitrary body returning *MergePullRequestResponse
func (c *ClientWithResponses) MergePullRequestWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*MergePullRequestResponse, error) {
	rsp, err := c.MergePullRequestWithBody(ctx, projectKey, repositorySlug, pullRequestId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMergePullRequestResponse(rsp)
}

func (c *ClientWithResponses) MergePullRequestWithResponse(ctx context.Context, projectKey string, repositorySlug string, pullRequestId int, params *MergePullRequestParams, body MergePullRequestJSONRequestBody, reqEditors ...RequestEditorFn) (*MergePullRequestResponse, error) {
	rsp, err := c.MergePullRequest(ctx, projectKey, repositorySlug, pullRequestId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMergePullRequestResponse(rsp)
}

// DeleteBranchWithBodyWithResponse request with arbitrary body returning *DeleteBranchResponse
func (c *ClientWithResponses) DeleteBranchWithBodyWithResponse(ctx context.Context, projectKey string, repositorySlug string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteBranchResponse, error) {
	rsp, err := c.DeleteBranchWithBody(ctx, projectKey, repositorySlug, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBranchResponse(rsp)
}

func (c *ClientWithResponses) DeleteBranchWithResponse(ctx context.Context, projectKey string, repositorySlug string, body DeleteBranchJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteBranchResponse, error) {
	rsp, err := c.DeleteBranch(ctx, projectKey, repositorySlug, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteBranchResponse(rsp)
}

// ParseGetCommitResponse parses an HTTP response from a GetCommitWithResponse call
func ParseGetCommitResponse(rsp *http.Response) (*GetCommitResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCommitResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RestCommit
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetPullRequestsResponse parses an HTTP response from a GetPullRequestsWithResponse call
func ParseGetPullRequestsResponse(rsp *http.Response) (*GetPullRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPullRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RestPullRequestPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreatePullRequestResponse parses an HTTP response from a CreatePullRequestWithResponse call
func ParseCreatePullRequestResponse(rsp *http.Response) (*CreatePullRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePullRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RestPullRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetPullRequestResponse parses an HTTP response from a GetPullRequestWithResponse call
func ParseGetPullRequestResponse(rsp *http.Response) (*GetPullRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPullRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RestPullRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMergePullRequestResponse parses an HTTP response from a MergePullRequestWithResponse call
func ParseMergePullRequestResponse(rsp *http.Response) (*MergePullRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MergePullRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RestPullRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteBranchResponse parses an HTTP response from a DeleteBranchWithResponse call
func ParseDeleteBranchResponse(rsp *http.Response) (*DeleteBranchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteBranchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
