import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "90-api-/kargo-api",
    },
    {
      type: "category",
      label: "System",
      items: [
        {
          type: "doc",
          id: "90-api-/admin-login",
          label: "Admin login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-config",
          label: "Delete the ClusterConfig",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-config",
          label: "Retrieve the ClusterConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-cluster-config",
          label: "Refresh the ClusterConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/get-public-config",
          label: "Retrieve public server configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-config",
          label: "Retrieve server configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-version-info",
          label: "Retrieve API Server version information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Core",
      items: [
        {
          type: "doc",
          id: "90-api-/list-projects",
          label: "List projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project",
          label: "Delete a Project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project",
          label: "Retrieve a Project resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-config",
          label: "Delete a ProjectConfig resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config",
          label: "Retrieve ProjectConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-project-config",
          label: "Refresh ProjectConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-project-config-maps",
          label: "List project-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-config-map",
          label: "Create a project-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-config-map",
          label: "Delete a project-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config-map",
          label: "Retrieve a project-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-config-map",
          label: "Patch a project-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-config-map",
          label: "Replace a project-level ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/query-freights-rest",
          label: "Query Freight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-freight",
          label: "Delete a Freight resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-freight",
          label: "Retrieve a Freight resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-freight-alias",
          label: "Patch a Freight resource's alias",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/approve-freight",
          label: "Approve Freight for promotion to a Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-images",
          label: "List container images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-promotion-tasks",
          label: "List PromotionTasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-promotion-task",
          label: "Retrieve a PromotionTask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-promotions",
          label: "List Promotions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-promotion",
          label: "Retrieve a Promotion",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/abort-promotion",
          label: "Abort a Promotion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/refresh-promotion",
          label: "Refresh a Promotion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-stages",
          label: "List Stages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-stage",
          label: "Delete a Stage",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-stage",
          label: "Retrieve a Stage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/promote-to-stage",
          label: "Promote to Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/promote-downstream",
          label: "Promote downstream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/refresh-stage",
          label: "Refresh a Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-warehouses",
          label: "List Warehouses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-warehouse",
          label: "Delete a Warehouse",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-warehouse",
          label: "Retrieve a Warehouse",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-warehouse",
          label: "Refresh a Warehouse",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-cluster-promotion-tasks",
          label: "List ClusterPromotionTasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-promotion-task",
          label: "Retrieve a ClusterPromotionTask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-config-maps",
          label: "List shared ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-config-map",
          label: "Create a shared ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-config-map",
          label: "Delete a shared ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-config-map",
          label: "Retrieve a shared ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-config-map",
          label: "Patch a shared ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-config-map",
          label: "Replace a shared ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-config-maps",
          label: "List system-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-config-map",
          label: "Create a system-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-config-map",
          label: "Delete a system-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-config-map",
          label: "Retrieve a system-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-config-map",
          label: "Patch a system-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-config-map",
          label: "Replace a system-level ConfigMap",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Cluster-Scoped Resource",
      items: [
        {
          type: "doc",
          id: "90-api-/list-projects",
          label: "List projects",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project",
          label: "Delete a Project",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project",
          label: "Retrieve a Project resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-cluster-analysis-templates",
          label: "List ClusterAnalysisTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-analysis-template",
          label: "Delete a ClusterAnalysisTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-analysis-template",
          label: "Retrieve a ClusterAnalysisTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-cluster-promotion-tasks",
          label: "List ClusterPromotionTasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-promotion-task",
          label: "Retrieve a ClusterPromotionTask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-config",
          label: "Delete the ClusterConfig",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-config",
          label: "Retrieve the ClusterConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-cluster-config",
          label: "Refresh the ClusterConfig",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Verifications",
      items: [
        {
          type: "doc",
          id: "90-api-/get-analysis-run",
          label: "Retrieve an AnalysisRun",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-analysis-run-logs",
          label: "Stream AnalysisRun logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-analysis-templates",
          label: "List AnalysisTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-analysis-template",
          label: "Delete an AnalysisTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-analysis-template",
          label: "Retrieve an AnalysisTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/reverify",
          label: "Reverify Freight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/abort-verification",
          label: "Abort a running Verification process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-cluster-analysis-templates",
          label: "List ClusterAnalysisTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-analysis-template",
          label: "Delete a ClusterAnalysisTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-analysis-template",
          label: "Retrieve a ClusterAnalysisTemplate",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Project-Level",
      items: [
        {
          type: "doc",
          id: "90-api-/get-analysis-run",
          label: "Retrieve an AnalysisRun",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-analysis-run-logs",
          label: "Stream AnalysisRun logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-analysis-templates",
          label: "List AnalysisTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-analysis-template",
          label: "Delete an AnalysisTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-analysis-template",
          label: "Retrieve an AnalysisTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-project-api-tokens",
          label: "List project-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-api-token",
          label: "Delete a project-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-api-token",
          label: "Retrieve a project-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-config",
          label: "Delete a ProjectConfig resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config",
          label: "Retrieve ProjectConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-project-config",
          label: "Refresh ProjectConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-project-config-maps",
          label: "List project-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-config-map",
          label: "Create a project-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-config-map",
          label: "Delete a project-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config-map",
          label: "Retrieve a project-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-config-map",
          label: "Patch a project-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-config-map",
          label: "Replace a project-level ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-project-events",
          label: "List project-level Kubernetes Events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/query-freights-rest",
          label: "Query Freight",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-freight",
          label: "Delete a Freight resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-freight",
          label: "Retrieve a Freight resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-freight-alias",
          label: "Patch a Freight resource's alias",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/approve-freight",
          label: "Approve Freight for promotion to a Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-project-generic-credentials",
          label: "List project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-generic-credentials",
          label: "Create project-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-generic-credentials",
          label: "Delete project-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-generic-credentials",
          label: "Retrieve project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-generic-credentials",
          label: "Patch project-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-generic-credentials",
          label: "Replace project-level generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-images",
          label: "List container images",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-promotion-tasks",
          label: "List PromotionTasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-promotion-task",
          label: "Retrieve a PromotionTask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-promotions",
          label: "List Promotions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-promotion",
          label: "Retrieve a Promotion",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/abort-promotion",
          label: "Abort a Promotion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/refresh-promotion",
          label: "Refresh a Promotion",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-project-repo-credentials",
          label: "List project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-repo-credentials",
          label: "Create project-level repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-repo-credentials",
          label: "Delete project-level repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-repo-credentials",
          label: "Retrieve project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-repo-credentials",
          label: "Patch project-level repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-repo-credentials",
          label: "Replace project-level repository credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-project-roles",
          label: "List project-level Kargo Role virtual resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-role",
          label: "Create a project-level Kargo Role virtual resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-role",
          label: "Delete a project-level Kargo Role virtual resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-role",
          label: "Retrieve a project-level Kargo Role virtual resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/update-role",
          label: "Update a project-level Kargo Role virtual resource",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/create-project-api-token",
          label: "Create a project-level API token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/grant",
          label: "Grant permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/revoke",
          label: "Revoke permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-stages",
          label: "List Stages",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-stage",
          label: "Delete a Stage",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-stage",
          label: "Retrieve a Stage",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/promote-to-stage",
          label: "Promote to Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/promote-downstream",
          label: "Promote downstream",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/refresh-stage",
          label: "Refresh a Stage",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/reverify",
          label: "Reverify Freight",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/abort-verification",
          label: "Abort a running Verification process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-warehouses",
          label: "List Warehouses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-warehouse",
          label: "Delete a Warehouse",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-warehouse",
          label: "Retrieve a Warehouse",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-warehouse",
          label: "Refresh a Warehouse",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Rbac",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-api-tokens",
          label: "List project-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-api-token",
          label: "Delete a project-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-api-token",
          label: "Retrieve a project-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-project-roles",
          label: "List project-level Kargo Role virtual resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-role",
          label: "Create a project-level Kargo Role virtual resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-role",
          label: "Delete a project-level Kargo Role virtual resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-role",
          label: "Retrieve a project-level Kargo Role virtual resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/update-role",
          label: "Update a project-level Kargo Role virtual resource",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/create-project-api-token",
          label: "Create a project-level API token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/grant",
          label: "Grant permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/revoke",
          label: "Revoke permissions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-system-api-tokens",
          label: "List system-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-api-token",
          label: "Delete a system-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-api-token",
          label: "Retrieve a system-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-system-roles",
          label: "List system-level Kargo Role virtual resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-system-role",
          label: "Retrieve a system-level Kargo Role virtual resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-api-token",
          label: "Create a system-level API token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-api-tokens",
          label: "List project-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-api-token",
          label: "Delete a project-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-api-token",
          label: "Retrieve a project-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-project-generic-credentials",
          label: "List project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-generic-credentials",
          label: "Create project-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-generic-credentials",
          label: "Delete project-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-generic-credentials",
          label: "Retrieve project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-generic-credentials",
          label: "Patch project-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-generic-credentials",
          label: "Replace project-level generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-project-repo-credentials",
          label: "List project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-repo-credentials",
          label: "Create project-level repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-repo-credentials",
          label: "Delete project-level repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-repo-credentials",
          label: "Retrieve project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-repo-credentials",
          label: "Patch project-level repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-repo-credentials",
          label: "Replace project-level repository credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/create-project-api-token",
          label: "Create a project-level API token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-generic-credentials",
          label: "List shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-generic-credentials",
          label: "Create shared generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-generic-credentials",
          label: "Delete shared generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-generic-credentials",
          label: "Retrieve shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-generic-credentials",
          label: "Patch shared generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-generic-credentials",
          label: "Replace shared generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-repo-credentials",
          label: "List shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-repo-credentials",
          label: "Create shared repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-repo-credentials",
          label: "Delete shared repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-repo-credentials",
          label: "Retrieve shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-repo-credentials",
          label: "Patch shared repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-repo-credentials",
          label: "Replace shared repository credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-api-tokens",
          label: "List system-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-api-token",
          label: "Delete a system-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-api-token",
          label: "Retrieve a system-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-system-generic-credentials",
          label: "List system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-generic-credentials",
          label: "Create system-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-generic-credentials",
          label: "Delete system-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-generic-credentials",
          label: "Retrieve system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-generic-credentials",
          label: "Patch system-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-generic-credentials",
          label: "Replace system-level generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/create-system-api-token",
          label: "Create a system-level API token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Config",
      items: [
        {
          type: "doc",
          id: "90-api-/delete-project-config",
          label: "Delete a ProjectConfig resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config",
          label: "Retrieve ProjectConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-project-config",
          label: "Refresh ProjectConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-config",
          label: "Delete the ClusterConfig",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-config",
          label: "Retrieve the ClusterConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-cluster-config",
          label: "Refresh the ClusterConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/get-public-config",
          label: "Retrieve public server configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-config",
          label: "Retrieve server configuration",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Singleton",
      items: [
        {
          type: "doc",
          id: "90-api-/delete-project-config",
          label: "Delete a ProjectConfig resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config",
          label: "Retrieve ProjectConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-project-config",
          label: "Refresh ProjectConfig",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-config",
          label: "Delete the ClusterConfig",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-config",
          label: "Retrieve the ClusterConfig",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/refresh-cluster-config",
          label: "Refresh the ClusterConfig",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Generic Config",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-config-maps",
          label: "List project-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-config-map",
          label: "Create a project-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-config-map",
          label: "Delete a project-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-config-map",
          label: "Retrieve a project-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-config-map",
          label: "Patch a project-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-config-map",
          label: "Replace a project-level ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-config-maps",
          label: "List shared ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-config-map",
          label: "Create a shared ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-config-map",
          label: "Delete a shared ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-config-map",
          label: "Retrieve a shared ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-config-map",
          label: "Patch a shared ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-config-map",
          label: "Replace a shared ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-config-maps",
          label: "List system-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-config-map",
          label: "Create a system-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-config-map",
          label: "Delete a system-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-config-map",
          label: "Retrieve a system-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-config-map",
          label: "Patch a system-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-config-map",
          label: "Replace a system-level ConfigMap",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-events",
          label: "List project-level Kubernetes Events",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Generic Credentials",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-generic-credentials",
          label: "List project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-generic-credentials",
          label: "Create project-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-generic-credentials",
          label: "Delete project-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-generic-credentials",
          label: "Retrieve project-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-generic-credentials",
          label: "Patch project-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-generic-credentials",
          label: "Replace project-level generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-generic-credentials",
          label: "List shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-generic-credentials",
          label: "Create shared generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-generic-credentials",
          label: "Delete shared generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-generic-credentials",
          label: "Retrieve shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-generic-credentials",
          label: "Patch shared generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-generic-credentials",
          label: "Replace shared generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-generic-credentials",
          label: "List system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-generic-credentials",
          label: "Create system-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-generic-credentials",
          label: "Delete system-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-generic-credentials",
          label: "Retrieve system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-generic-credentials",
          label: "Patch system-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-generic-credentials",
          label: "Replace system-level generic credentials",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Repo Credentials",
      items: [
        {
          type: "doc",
          id: "90-api-/list-project-repo-credentials",
          label: "List project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-project-repo-credentials",
          label: "Create project-level repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-project-repo-credentials",
          label: "Delete project-level repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-project-repo-credentials",
          label: "Retrieve project-level repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-project-repo-credentials",
          label: "Patch project-level repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-project-repo-credentials",
          label: "Replace project-level repository credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-repo-credentials",
          label: "List shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-repo-credentials",
          label: "Create shared repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-repo-credentials",
          label: "Delete shared repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-repo-credentials",
          label: "Retrieve shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-repo-credentials",
          label: "Patch shared repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-repo-credentials",
          label: "Replace shared repository credentials",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      items: [
        {
          type: "doc",
          id: "90-api-/delete-resource",
          label: "Delete resources",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/create-resource",
          label: "Create resources",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/update-resource",
          label: "Update resources",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Shared",
      items: [
        {
          type: "doc",
          id: "90-api-/list-cluster-analysis-templates",
          label: "List ClusterAnalysisTemplates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-cluster-analysis-template",
          label: "Delete a ClusterAnalysisTemplate",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-analysis-template",
          label: "Retrieve a ClusterAnalysisTemplate",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-cluster-promotion-tasks",
          label: "List ClusterPromotionTasks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-cluster-promotion-task",
          label: "Retrieve a ClusterPromotionTask",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-config-maps",
          label: "List shared ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-config-map",
          label: "Create a shared ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-config-map",
          label: "Delete a shared ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-config-map",
          label: "Retrieve a shared ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-config-map",
          label: "Patch a shared ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-config-map",
          label: "Replace a shared ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-generic-credentials",
          label: "List shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-generic-credentials",
          label: "Create shared generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-generic-credentials",
          label: "Delete shared generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-generic-credentials",
          label: "Retrieve shared generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-generic-credentials",
          label: "Patch shared generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-generic-credentials",
          label: "Replace shared generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-shared-repo-credentials",
          label: "List shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-shared-repo-credentials",
          label: "Create shared repository credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-shared-repo-credentials",
          label: "Delete shared repository credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-shared-repo-credentials",
          label: "Retrieve shared repository credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-shared-repo-credentials",
          label: "Patch shared repository credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-shared-repo-credentials",
          label: "Replace shared repository credentials",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "System-Level",
      items: [
        {
          type: "doc",
          id: "90-api-/list-system-api-tokens",
          label: "List system-level API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-api-token",
          label: "Delete a system-level API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-api-token",
          label: "Retrieve a system-level API token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/list-system-config-maps",
          label: "List system-level ConfigMaps",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-config-map",
          label: "Create a system-level ConfigMap",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-config-map",
          label: "Delete a system-level ConfigMap",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-config-map",
          label: "Retrieve a system-level ConfigMap",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-config-map",
          label: "Patch a system-level ConfigMap",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-config-map",
          label: "Replace a system-level ConfigMap",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-generic-credentials",
          label: "List system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-generic-credentials",
          label: "Create system-level generic credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "90-api-/delete-system-generic-credentials",
          label: "Delete system-level generic credentials",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "90-api-/get-system-generic-credentials",
          label: "Retrieve system-level generic credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/patch-system-generic-credentials",
          label: "Patch system-level generic credentials",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "90-api-/update-system-generic-credentials",
          label: "Replace system-level generic credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "90-api-/list-system-roles",
          label: "List system-level Kargo Role virtual resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/get-system-role",
          label: "Retrieve a system-level Kargo Role virtual resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "90-api-/create-system-api-token",
          label: "Create a system-level API token",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
