{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kargo.fullname" . }}-api
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "kargo.selectorLabels" . | nindent 4 }}
    {{- include "kargo.api.labels" . | nindent 4 }}
{{- end }}
