{
  "openapi": "3.0.0",
  "info": {
    "title": "Bitbucket API",
    "description": "Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.",
    "version": "2.0",
    "termsOfService": "https://www.atlassian.com/legal/customer-agreement",
    "contact": {
      "name": "Bitbucket Support",
      "url": "https://support.atlassian.com/bitbucket-cloud/",
      "email": "support@bitbucket.org"
    }
  },
  "servers": [
    {
      "url": "https://api.bitbucket.org/2.0"
    }
  ],
  "paths": {
    "/repositories/{workspace}/{repo_slug}/pullrequests": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns all pull requests on the specified repository.\n\nBy default only open pull requests are returned. This can be controlled\nusing the `state` query parameter. To retrieve pull requests that are\nin one of multiple states, repeat the `state` parameter for each\nindividual state.\n\nThis endpoint also supports filtering and sorting of the results. See\n[filtering and sorting](/cloud/bitbucket/rest/intro/#filtering) for more details.",
        "summary": "List pull requests",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      },
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Creates a new pull request where the destination repository is\nthis repository and the author is the authenticated user.\n\nThe minimum required fields to create a pull request are `title` and\n`source`, specified by a branch name.\n\n```\ncurl https://api.bitbucket.org/2.0/repositories/my-workspace/my-repository/pullrequests \\\n    -u my-username:my-password \\\n    --request POST \\\n    --header 'Content-Type: application/json' \\\n    --data '{\n        \"title\": \[...]",
        "summary": "Create a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}": {
      "get": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Returns the specified pull request.",
        "summary": "Get a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}/merge": {
      "post": {
        "tags": [
          "Pullrequests"
        ],
        "description": "Merges the pull request.",
        "summary": "Merge a pull request",
        "security": [
          {
            "oauth2": [
              "pullrequest:write"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:pullrequest:bitbucket",
              "write:pullrequest:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    },
    "/repositories/{workspace}/{repo_slug}/commit/{commit}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Returns the specified commit.",
        "summary": "Get a commit",
        "security": [
          {
            "oauth2": [
              "repository"
            ]
          },
          {
            "basic": []
          },
          {
            "api_key": []
          }
        ],
        "x-atlassian-oauth2-scopes": [
          {
            "state": "Current",
            "scheme": "oauth2",
            "scopes": [
              "read:repository:bitbucket"
            ]
          }
        ],
        "x-atlassian-auth-types": [
          "forge-oauth2",
          "api-token"
        ]
      }
    }
  },
  "components": {
  }
}
