
{{- if or (and .Values.webhooksServer.enabled .Values.webhooksServer.tls.selfSignedCert) (and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled .Values.api.oidc.dex.tls.selfSignedCert) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "kargo.fullname" . }}-selfsigned-cert-issuer
spec:
  selfSigned: {}
{{- end }}
