apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
  {{- include "kargo.annotations" (dict "root" .) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-admin
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-admin
