{{- if and .Values.dataPlane.install .Values.global.sharedResources.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  {{- include "kargo.annotations" (dict "root" . "annotations" .Values.global.sharedResources.extraNamespaceAnnotations) | nindent 2 }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
  {{- with .Values.global.sharedResources.extraNamespaceLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.global.sharedResources.namespace }}
{{- end }}
