{{- if .Values.global.sharedResources.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.sharedResources.namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
  {{- include "kargo.annotations" (dict "root" .) | nindent 2 }}
{{- end }}
