apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo-kit.fullname" . }}-kargo-api
  labels:
    {{- include "kargo-kit.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "kargo-kit.fullname" . }}-kargo-api-token
  annotations:
    kubernetes.io/service-account.name: {{ include "kargo-kit.fullname" . }}-kargo-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kargo-kit.fullname" . }}-kargo-controller
  labels:
    {{- include "kargo-kit.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "kargo-kit.fullname" . }}-kargo-controller-token
  annotations:
    kubernetes.io/service-account.name: {{ include "kargo-kit.fullname" . }}-kargo-controller
