apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kargo-kit.fullname" . }}
  labels:
    {{- include "kargo-kit.labels" . | nindent 4 }}
webhooks:
- name: stage.kargo.akuity.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    url: {{ .Values.webhooks.server }}/mutate-kargo-akuity-io-v1alpha1-stage
    caBundle: {{ .Values.webhooks.caBundle }}
  rules:
  - scope: Namespaced
    apiGroups: ["kargo.akuity.io"]
    apiVersions: ["v1alpha1"]
    resources: ["stages"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kargo-kit.fullname" . }}
  labels:
    {{- include "kargo-kit.labels" . | nindent 4 }}
webhooks:
- name: stage.kargo.akuity.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    url: {{ .Values.webhooks.server }}/validate-kargo-akuity-io-v1alpha1-stage
    caBundle: {{ .Values.webhooks.caBundle }}
  rules:
  - scope: Namespaced
    apiGroups: ["kargo.akuity.io"]
    apiVersions: ["v1alpha1"]
    resources: ["stages"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
- name: promotion.kargo.akuity.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    url: {{ .Values.webhooks.server }}/validate-kargo-akuity-io-v1alpha1-promotion
    caBundle: {{ .Values.webhooks.caBundle }}
  rules:
  - scope: Namespaced
    apiGroups: ["kargo.akuity.io"]
    apiVersions: ["v1alpha1"]
    resources: ["promotions"]
    operations: ["CREATE", "UPDATE", "DELETE"]
  failurePolicy: Fail
