{{- if .Values.rbac.installGlobalResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8sta.controller.fullname" . }}
  labels:
    {{- include "k8sta.labels" . | nindent 4 }}
    {{- include "k8sta.controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - k8sta.akuity.io
  resources:
  - environments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8sta.akuity.io
  resources:
  - environments/status
  verbs:
  - update
{{- end }}
