{{- if or .Values.controller.argocd.watchArgocdNamespaceOnly .Values.controller.argocd.enableCredentialBorrowing }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-controller
  namespace: {{ .Values.controller.argocd.namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
rules:
{{- if or .Values.controller.argocd.watchArgocdNamespaceOnly }}
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - patch
  - watch
{{- end }}
{{- if .Values.controller.argocd.enableCredentialBorrowing }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
{{- end }}
