{{- if and .Values.argocd.dataPlane.install .Values.controller.enabled .Values.controller.argocd.integrationEnabled .Values.controller.argocd.watchArgocdNamespaceOnly }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kargo.controller.fullname" . }}
  namespace: {{ .Values.controller.argocd.namespace | default "argocd" }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
  {{- include "kargo.annotations" (dict "root" .) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kargo.controller.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "kargo.controller.fullname" . }}
{{- end }}
