{{- if and .Values.api.enabled .Values.api.oidc.enabled .Values.api.oidc.dex.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: 
  name: {{ include "kargo.dexServer.fullname" . }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.dexServer.labels" . | nindent 4 }}
data:
  config.yaml: |-
    issuer: {{ .Values.api.address }}/dex

    storage:
      type: memory

    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls.crt
      tlsKey: /etc/dex/tls.key
    telemetry:
      http: 0.0.0.0:5558

    staticClients:
    - id: kargo
      name: Kargo
      public: true

    connectors:
    {{- toYaml .Values.api.oidc.dex.connectors | nindent 4 }}
{{- end }}
