apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-kargo-dev-cluster
product: kind
registry: kargo-dev-registry
kindV1Alpha4Cluster:
  nodes:
  - extraPortMappings:
    - containerPort: 30080 # Argo CD
      hostPort: 30080

