apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-kargo-dev-cluster
product: kind
registry: kargo-dev-registry
kindV1Alpha4Cluster:
  nodes:
  - extraPortMappings:
    - containerPort: 30080 # Istio HTTP
      hostPort: 30080
    - containerPort: 30081 # Argo CD
      hostPort: 30081
    - containerPort: 30082 # Kargo Server
      hostPort: 30082

