apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: kind-kargo-dev-cluster
product: kind
registry: kargo-dev-registry
kindV1Alpha4Cluster:
  nodes:
  - extraPortMappings:
    - containerPort: 30080 # Argo CD
      hostPort: 30080
    - containerPort: 30081 # Kargo API server
      hostPort: 30081
    - containerPort: 30082 # Kargo API server proxy
      hostPort: 30082
