{{- if and .Values.garbageCollector.enabled .Values.rbac.installClusterRoleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-garbage-collector
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.garbageCollector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-garbage-collector
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-garbage-collector
{{- end }}
