{{- if and .Values.dataPlane.install .Values.global.systemResources.createNamespace }}
{{- include "kargo.validateNoLegacySecretNamespaces" . }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ quote .Values.global.systemResources.namespace }}
  labels:
    {{- include "kargo.componentLabels" (dict "root" . "labels" .Values.global.systemResources.extraNamespaceLabels) | nindent 4 }}
  {{- include "kargo.annotations" (dict "root" . "annotations" .Values.global.systemResources.extraNamespaceAnnotations) | nindent 2 }}
{{- end }}
