apiVersion: v1
kind: Secret
metadata:
  name: kargo-test-gpg-signing-key
  namespace: kargo
type: Opaque
stringData:
  signingKey: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----

    lQcYBGmyJr0BEADd/Zhbf+xKK6FZx8L69j8XJjo5dZprPNIabhams70U81QQx2wM
    KQ+yX0RYtww2Tt70pTquT92furvRkTMtRp9ELFHzj/9g96AqdLFpS/R4y+3UXsP5
    hhzZTN9W0cmVL4dL3V36oi6qfKybCk8RNoKsG2Q0COh2WM7nYKpI9ZiBCxDm7cwQ
    ymo1HVNVy5oT5j5ERQOittod/TxllY1u+VLczevZQF8SO9tyHn8AI8qpHBoiB2PQ
    f7xEin0LA10DBTy+E6d4H5att4/HzWO5fRIFKra+XN4naO2StsQ5hv1uKFkxi3oG
    yQ1hhDPHojd8zJRIrzaWmtn00DoH0gWdB+QYCF3SCEiN29ADFC9syk3zGMpJ8d5P
    yoGNmEoM3uAl5FZM9CKW8lTmCilM1E2otaWcs+YyiPIwxDrWgpxHivCK+U1pNWPI
    +a0ebCW9O9DN/iKU5RlLDif+Cd4P4p5FIu2YRUaWIm9oY5u0snl1pjvnMdlV89Tf
    ZNa/ByVbrdrVMgTk81YvT89QR73Haa7VehXQvgNTScUXNV81giL6LkBhHGSwLab4
    u77QRnE4ADMxf1AA/qyrMce1KWK0EhXpCkpmJAs0QrnFEE/FgoUJsFInVaKVNWBO
    6MLpxCgOfQxTYWBs8QpgnQZlQ3B9wGLCUJwy8nttpaX2XmchdXwQR9GVSQARAQAB
    AA/7ByU6Cbvw4aRM4cRt0MErX7XhyuavrUL8alBf10bSz8FTU+TvY+bQdAff/dEK
    ihb40zwcSu8ULaeHkyPO12a+CqY4jxPz/u2JkMRHz6FbwaWixqK0QSxhclcomzVO
    fUhV3QnHlCEzSlaQAb+PsvijtSF+lLQys1iBdG4mnQmWupSeGyjNWD8Dsyj5/Tl8
    AKb5Gx5zkwG6vJthnc12C3voAGZ6cHhDdyVJF3/Gy7zbMZ1PdAfz3Qq3hydEBh46
    GLZK8b1VNychJP9TF/XS/234rgTlc/QuTGtytjW+1DE1qB2RXWhlaaGAFkL4nbTp
    f1FgdoR5R9i9KkWnkIfgmWDfJR2JPBhfiPsinQ0SeFw1Q4tJZCG/5xLUD5SWBtYX
    F/ZFX1rDlg4CRtqw8ZQp/OEUz7f0ssdDG3heCWysuXg9LyztdA59EK/tocGK+GVQ
    WJJDPglCHNDB5ZFkSQ7YxZipGQuJC3k+6oe1KVm4ieW44Ybjw7PQK8nEDNFbtyek
    61+bE4j8XPHG5IYBIKvbvLeByAq6r206Eh9c283PK1edWP9gP2WHaw0ScIBaU7mV
    msNuJ3DBhbs+I3yOiQxu3L5VTqvAPF9VSbkZCho5ZdDjLWnreGJu2kwyqcYg5kss
    RMN4XCDjcrcTdktEVzjArhZVKLNeb47+5gmfnw9d3BQ934EIAOc+bRA7j3aRdR8+
    SE/l8cjsIVRP3LobHo3nzpbPB7P2ikuK531wPqur0F7VHlujqJcS0p6ZAnaV1aza
    Cbt2hPB3Ec5z+Yjk1at+oEQdlW4voung/FTde35Y2CL8wCpDyqI50eduLG4aVPR1
    4Lz4vAlkM/wNZIGgn+UAuME2el7K9S5yHtRrY6IQdSlZdLVv0gV8LqLYQpCGfzqz
    VTkYqTOq85C143JPM2AMGqb04ARpIFvKYvpvsHkFByFXy/jqnrfquh9AxgFQPLL7
    EDZaY34nxnWMGmRRh9Q4roxh/53bJWrijBf9Wj3HRnYweOFk9LyNtio1TVzt+h3X
    XefYNykIAPXBkgod8Mhw9IpjltWXD4ElZ4V2kFfsTNxwBs7HwITMDiATEMW8j/OK
    IpT0YPX8wnIWk8zAXaKXvXT1njtnZ+T2BGbcflClIRvS/Z+RAzaX1Nsace7If5jy
    r9BmD98IniuvgOdIYDq3MC9frSaS7gXGbgxs0KIQIIpDJ+L8NtcOHC2DDIVcfDk6
    MatCUObPbpwK2x8ByGUjFTg1jqeGbEb9PPlQ4kII0M4F9lft4LyBMnDjzPJ9fUr4
    c7mY5YYcurvO6Ts9KT5bErMUvW5wmUtzAQCap451oijj+g2Z5CXs2DXuHOfMI2MH
    JY+ApDT+7g1CAdInav2CiVaup4/a0SEIAMpGgFj1F+JbnCYv8IO4fLF6bPVeXFcR
    5LAQA7zfmES0ghJUM6N0Ksr4cm7IMwQ9jmlcz3D/0rrBWFo38oFF5snYOsjmFXcT
    jJr8cIh19RSAkjKdj5MKyQuEbtqWblHziW1q5SDIf+cUSaV+gOkO6M4gCXiKYIps
    YLHoNGDDm7i/nxsFPQ6J5UXKU73LCBjRAKHiR+OLgBj9jZnGYor2Qw8AOgMKgWfT
    GJBiuvYuhmpEIl9CTT8RJP7fqDw3taubJE5VCQFJ6aCebwThN+ms1I0+gfzDu5V1
    SyKcbCtnQtSqqKHJbYwp6Gbh3jp1LiD5g3g8+chNgU6SBUhc6PNF7vN8RLQiS2Fy
    Z28gVGVzdCBLZXkgPG5vLXJlcGx5QGthcmdvLmlvPokCUgQTAQgAPBYhBCRrxTni
    jUkF34GjRl818mRiDs0nBQJpsia9AxsvBAULCQgHAgIiAgYVCgkICwIEFgIDAQIe
    BwIXgAAKCRBfNfJkYg7NJ7YkD/9LYlG+kXwCi7CD1bkf1AAQH84ldvy3/u1ur5HV
    LFTeabrVjr4ePT+oYwR8z9HHc3V9dlirMLUUyGxhAz4hmJLNtOLTXHF7aA2fUdh4
    LLEAjVj+eT/uj9VPq7BmaySZIFndOPK5eNDQZEYShjpIJsLEoG1OS1UcsR04Yvrm
    msxKu8w+vYmII0bOogpyiR+hlNWxvhWq4PmXR5dXCUOyVXUhb1lyDV/wNB1Yr7+e
    1S9hvCvXkAZ2YfER6bs0dcwGyEjQSjMOLN4vjMrpf8dGPjQZGFqJGZsEvOJ7d/Z9
    ixUxjEU1dOw622KsuvCW6bZforQvTksIGm9sQR1aMhaiqjdiADfMGEG8qvaI0AdF
    WtVggG8BYFzyMOLfB74X74gM47fOVuuSLGEUN20vYyFIB99TMdDHTe//R4lBEyoh
    /YjMZnSpV8iy9pnKNVvJYy1E6//P4IkZn8pGrYisrZekY5a6bq6ElJriBxg4WsBj
    LPZG/sWEtQyXkUP1FS9xna8uLIFq6dd/2IDUheB13BnRDVrjX7Iqv8QscKEUS7m6
    hVr01D+FxD/PBNxVqDQs+12cEIRV8JjzBZjcFAmP/nZRc887TrNQ2hOK2kypyjiF
    Yie5CR9wlEoKVZN53ro8tnLI0uSLaA+bKlfPoL1tYrquvlNO4AdEWYl9AvBuChv2
    iLHwN50HGARpsia9ARAAnHQFiuKoouRbDL5eTRwsrGyUVi8tUz/8bTaBh6mGPO0H
    jTyhkCriyXWjfYciEza+80cx4SXnuhe1KLH/AuUZMO2yvxH4cEUrcWrUGbAXiw83
    xvCJwLLX30eTlJBz1T+FcJsH09gGSeLKmv/tt/C7xjbt56V5Kt078jhgo218NKhC
    zUtMBqF+wg+61pVy6ROif4fh5IACYFW//RIC9qbmqBh/rwe8SuONXjHQRPcImyVI
    F/mrYCuuJ2B1S+i5m2P5zLIXDi9HiUogLltYh0zxv0Ll7DSPg+vVGP/dQ7DytZW4
    h+QZNzpPGcgCDNEjlfAoMR4OP5KVwTSpRpPevus4pVhB/suTN2bMMPbmTuvVgYtl
    fOhcUsWqwU8m0r2kNp6ChxQSTRulflR6TWUM4RnEr2wKLg/bVPTykbC/O71sLDMB
    je6SKu8QnulW24TtG3ROPrLzX4bycisjw3tE1ewuPmVqzm5XPzL4mYKulKjv+L5s
    oZP9lJ2XQ4FpEGmuZRuNq6IyrMsGOujRN7YYGL/t0rrBqC6NVd2n20j4X5JJS8Wj
    SGse1j5zKR0L7eEnrJ6J+HnWmzyvJByG5uVytNZJmi7HJ8BmXxlC4fkQFDheH4G9
    M3wRtE9zBVTeouEqZUkO4ofOeqLoIZSo43X63GA++6PGhq+6sdBLd1WRk0MW4wMA
    EQEAAQAP+wSf2hpaxBbCXqh2xaO7UDIx269C3Zc9fSM0d/ibtU26QGQGZ6H/mwyb
    pZ8jo3hFhR64ahKNrFbJnDTfiCTafreoY0EKKQIW7qVU112Svvfv4llPerDAlEZg
    ZhqqARBcxOX16c+mdmRSsoZFJaf8I/YRLj7lEn8PQQDSMWIhIO/cLvVNSZkg1/Xb
    0l4rXzuMCrHFHyzsmdiUlIzIe08kjg00+6PbZpxDAGjJOIyr+FjRXLB/qbtS/ABb
    sXedQ7t6B6H8SM8bhoTq8NpN7Qk6xgCkhk3RHHBTVTN+s4uGEcNLV9UOC4zCsCBC
    5HONu8k1Hj419UjssptJCJkyUuz6JKiDMcb8sgHxlyjTJ8xdDTuW27+sSKnOKgYA
    TZDt6ro1sxzHlyJcI1D4sGuO4r1gJEfHHXZzCya8oYSvuiK8WSHai1Hl1e2vYJuC
    YQRbDbl0Gh55JZHbtJ7gzWAyqkD4KdvVqwtk8B0GZXj4dfobtokbtwZhtAxU5oW+
    Ql9mbZHw/M0lz4AO2HSgrS/7nb2EhdZmyBLUZpSA9vaJiW+TEqnEqMRiZei3xFmL
    uyKsmAxk5h/k4JNsCFx3MfgMzd5FxcqkyfksvThC4f1Di2NkQufhM60tfCJo8jPL
    Ver7hHDy51paYnR4XoKUSFHj86zNtYILqrd+dxt9+IyCfdP+Ay7ZCADFIVCaM+CA
    YtvVIBnqMaVuq1VM4mry4tUYzF5nURMEh1Bg8bNz5n3d+hvNvHyrgcWOfeRpEYjG
    u3+QJTHhF2DhDOjW0cjnzdb59YsaFXC0RDNgPK+kbtSNH3Cxf2yv9m7UCwITn6It
    HQrto5cBXxcpskA8+utqCdbmTOaj8pNBFUlNVxIp5NOqSnh7VPl36Hw17uHe+MCu
    pXaTktOjsWrdTSo/ji4u/Ygo6QibhRmeLcWRScloSn1qudhvsL6Q8aRzrxNx0Fpm
    +0YGC1oUFSGBlEOHTSdLGQTf+I2eCX0Dl8OikIKO1b3iypDgyfh9Esg2mT+uvKoR
    boRjau9ehJDPCADLLPAei6rlvK86adwWKOFysDeMs3OGMIFTuOeyW6+X1UQjsJ6U
    WDlwLRSHlWUiMecZfxy7RaVorDtcupfM90giSWlouSR+BRa+psYsxbcSfUbqdv84
    XBqR/hgxyYMZkoNFk+udkq1DaTH6Ohy77fM2Y0Bj4NVtSa0ifa0bZBvWvgUtzevi
    iB8SGBvMbrqCi2nxZmXmKgtB4YSCXwMlooZUpAn2ybtRgowbUEtSZw26Axe8vrd6
    Hda+IXz2QedFOHhGcZ91iXRw7WGm1EUwCvMCQPTypbYP7ThvvR4IV+IqD4xoFRLH
    ddi4+5yLWH1LPhC3oy56fFlGNbgtEswWuQ+NB/oDb2TERqjo6OqDOATmCqrXvotJ
    UGaxlR2gUcMcWTzZNlM9SuSxRnnFWtfzC070NKoskojKmGg1wrxU8aECZCpHY9zs
    K5ojdVtFux1tNhI/iECnAKwTTmZpW4POyJ96gSjqXpOp5KV8D1bsg1Gxd8ERJrTy
    maEbCq0JL0vE7jknUJrq7cPBdHAclledC9rHDkOO8P2hUK4mo+tF0F/IZVK5onwQ
    vRpH5/XsrwHMcO7ccXMyKH5beylwYOQbMscPI5gNep6aV1grzKeXqUaFrG0FdEXu
    mHUdLMzzh6oxXUIvpJlLmH9wCKXDbBbqpXGqyQ0NR2bsNeoAmARGf0WM/WylfPWJ
    BGwEGAEIACAWIQQka8U54o1JBd+Bo0ZfNfJkYg7NJwUCabImvQIbLgJACRBfNfJk
    Yg7NJ8F0IAQZAQgAHRYhBHVLkGQ1NkxEA8rb+4ObB2DoSD1FBQJpsia9AAoJEIOb
    B2DoSD1FF/cP/jXm7ssd77zPC1GCZx0srX8JE2DrSRNp/utHtvk29YAbD5GK3Dxi
    2t7rCMJGYPK0VTImC74TeAvABlPtt/K/vUl/4vVekSX0r9/4fhQH61S5S6BsfYpb
    qYUmhRoOPeiEod0iPnE0eLPzS3FZDxENjJ9n29tZv2JgZpgKj1CaOJxGuhLwsE6m
    jXFfwQmxSrRXQ+ZwR64Sr7VXG5cuFCYdvgPalyy2/2TzwBMx3CJODwm6tedP978f
    St1p+tPLQO9pUcmi+c3bCZ5A8jYvhUIal9FqCkm+tx/c0CkDIZ57v2uznJa9C5Zt
    gPtAo93ORf8D4Cc/nZw2BfQ1qxV1n/qyhWSu9fDobHCWznC/R2OTVrfn+BbgQste
    fodnydxtgb63B2pwxG4QZ/t8OE6mf9v2dODmibQ299OwbJS6vRpqQiBAIxfLcrBy
    DDLTa4946H3EcpJWKdgksKUXY59X8UxvL7XUH4CnSqpj8BK+8CAyWqb6vjgt5Fn2
    lCibCfAH30Sq95tlKpIsq+rXI5TRnPz9R9efMxiCdjo1QJF56H13EUdINn5+Cky/
    z8eZmJ6MbqmA84INEp3W6VY/31LVqSnkMsEqDQ3+qZ5goZBwazcjd1viMrMZIN5l
    mQpGZukWZZle0EfUXrn54WkJKyECGU+31mte9Cl7ZqMvOKgGCEica34EVuUP/j6z
    ZntpqxiJjw84b9l82rMvJ20cDLEm4EgjZHMfh3SeeD6ylfLYoSi27qciVGHZ3e6t
    4swvutHNFcwbltRzpZXNIJ0Hjs0nE7ePkEAnHaRIkxPaPFuOauXbYdxErms0pTug
    GGioZwMADO6zPxjLlTodo4PyRZWGScMRUh7IBLt6boTgUgsbAZO8bJr6U7lZCDZ3
    r8wt7qjMkC1zkEs4VgQNDxJKFukVZ/zWkw1VDwlxgIHs2AVz7oEU0NxsBSlUKYRp
    qNi7NWKF21zlrhm4T9WlKQTcuo0Ii+cRkTDhC+DIgwlmo3dB27pS9KuEp+BhXH5o
    NPrGjir7AoxeJD0ObKChtRiQ0HXJj9mnSyf/C63t2DeIe/oH1Vo/9eRumzFivpRU
    IVG/IAfemP7X8uy8+3xhC4ZQEP+xkFHOT9gvtiPBRyTOIxZYccUi1zh4eF0anD3q
    I8yQHE6VozEm14cZn4O5cYfUZ4G6IwB9urVdi7Sg5HgAvMlOBIB5uS3UiKLp59q3
    KwUt0H+hNxmroTmXfNLhHkv23DrN2kMbhHjQfUCRqslVOMTcKGiID1nG4gE8IbMU
    PkJ7eicfM7txaKiF69jxkzIyVeCsfsLNZUThGxyE/qaVz9YEKjpMWGqv7+oIcUUW
    rG3zXpnnzYbbLR5r+tEFfW0Hjk1Y08estSXIUE6J
    =t/xA
    -----END PGP PRIVATE KEY BLOCK-----
