{{- if .Values.argocd.enableCredentialBorrowing }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd-kit.fullname" . }}-kargo-controller
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "argocd-kit.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
