package git

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sync"
	"time"

	libExec "github.com/akuity/kargo/pkg/exec"
)

const (
	// DefaultMaxCacheEntries is the default maximum number of cached bare repos.
	DefaultMaxCacheEntries = 100
)

// RepoCache is a thread-safe cache of bare git repositories keyed by URL +
// credential hash. It avoids redundant clones when multiple callers need
// access to the same repository by maintaining a shared bare clone and handing
// out independent worktrees.
//
// When the cache exceeds MaxEntries, the least recently used entry is evicted.
type RepoCache struct {
	baseDir    string
	maxEntries int

	mu      sync.Mutex
	entries map[string]*repoCacheEntry
}

type repoCacheEntry struct {
	mu         sync.Mutex
	bare       BareRepo
	lastAccess time.Time
}

// RepoCacheOptions configures a RepoCache.
type RepoCacheOptions struct {
	// BaseDir is the directory in which cached bare repos will be stored.
	// If empty, os.TempDir() is used.
	BaseDir string
	// MaxEntries is the maximum number of cached bare repos. When exceeded,
	// the least recently used entry is evicted. Defaults to DefaultMaxCacheEntries.
	MaxEntries int
}

// NewRepoCache creates a new RepoCache.
func NewRepoCache(opts *RepoCacheOptions) *RepoCache {
	if opts == nil {
		opts = &RepoCacheOptions{}
	}
	baseDir := opts.BaseDir
	if baseDir == "" {
		baseDir = os.TempDir()
	}
	maxEntries := opts.MaxEntries
	if maxEntries <= 0 {
		maxEntries = DefaultMaxCacheEntries
	}
	return &RepoCache{
		baseDir:    baseDir,
		maxEntries: maxEntries,
		entries:    make(map[string]*repoCacheEntry),
	}
}

// cacheKey returns a key that uniquely identifies a repo URL + credential
// combination. This ensures that different credentials for the same repo
// (e.g., from different Kargo projects) get separate cache entries, preventing
// cross-project credential leakage.
func cacheKey(repoURL string, clientOpts *ClientOptions) string {
	if clientOpts == nil || clientOpts.Credentials == nil {
		return repoURL
	}
	h := sha256.New()
	h.Write([]byte(clientOpts.Credentials.Username))
	h.Write([]byte{0})
	h.Write([]byte(clientOpts.Credentials.Password))
	h.Write([]byte{0})
	h.Write([]byte(clientOpts.Credentials.SSHPrivateKey))
	return fmt.Sprintf("%s@%x", repoURL, h.Sum(nil)[:8])
}

// GetWorkTree returns a Repo backed by an independent worktree from a cached
// bare clone of the given repository URL. On first access, the repo is cloned
// as a bare repo. On subsequent access, refs are fetched to update the cache.
// The returned Repo must be closed by the caller when done.
//
// Cache entries are keyed by (repoURL, credentialHash) to ensure that
// different credentials for the same repo URL get separate cache entries.
// This prevents cross-project credential leakage when multiple Kargo projects
// subscribe to the same repository with different credentials.
func (c *RepoCache) GetWorkTree(
	repoURL string,
	clientOpts *ClientOptions,
	cloneOpts *CloneOptions,
) (Repo, error) {
	if clientOpts == nil {
		clientOpts = &ClientOptions{}
	}
	if cloneOpts == nil {
		cloneOpts = &CloneOptions{}
	}

	key := cacheKey(repoURL, clientOpts)
	entry := c.getOrCreateEntry(key)

	// Lock per-URL so concurrent access to different URLs is not serialized.
	entry.mu.Lock()
	defer entry.mu.Unlock()

	entry.lastAccess = time.Now()

	if entry.bare == nil {
		// First access: bare clone
		bare, err := CloneBare(repoURL, clientOpts, &BareCloneOptions{
			BaseDir: c.baseDir,
		})
		if err != nil {
			return nil, fmt.Errorf("error cloning bare repo %q into cache: %w", repoURL, err)
		}
		entry.bare = bare
	} else {
		// Subsequent access: update credentials and fetch
		if err := c.updateCredsAndFetch(entry.bare, clientOpts); err != nil {
			return nil, fmt.Errorf("error fetching updates for cached repo %q: %w", repoURL, err)
		}
	}

	// Create an independent worktree for the caller
	return c.createWorkTreeRepo(entry.bare, cloneOpts)
}

// getOrCreateEntry returns the cache entry for the given key, creating one if
// it doesn't exist. If the cache is at capacity, the least recently used entry
// is evicted first. The key should be generated by cacheKey().
func (c *RepoCache) getOrCreateEntry(key string) *repoCacheEntry {
	c.mu.Lock()
	defer c.mu.Unlock()

	if entry, ok := c.entries[key]; ok {
		return entry
	}

	// Evict LRU entry if at capacity
	if len(c.entries) >= c.maxEntries {
		c.evictLRULocked()
	}

	entry := &repoCacheEntry{}
	c.entries[key] = entry
	return entry
}

// evictLRULocked removes the least recently used cache entry. Must be called
// with c.mu held.
func (c *RepoCache) evictLRULocked() {
	var oldestKey string
	var oldestTime time.Time

	for key, entry := range c.entries {
		// Try to check lastAccess without blocking. If the entry is locked
		// (actively in use), skip it — don't evict active entries.
		if !entry.mu.TryLock() {
			continue
		}
		if oldestKey == "" || entry.lastAccess.Before(oldestTime) {
			oldestKey = key
			oldestTime = entry.lastAccess
		}
		entry.mu.Unlock()
	}

	if oldestKey == "" {
		return // All entries are actively in use; skip eviction
	}

	entry := c.entries[oldestKey]
	entry.mu.Lock()
	if entry.bare != nil {
		entry.bare.Close() // nolint: errcheck
	}
	entry.mu.Unlock()
	delete(c.entries, oldestKey)
}

// updateCredsAndFetch updates credentials on the cached bare repo and fetches
// the latest refs from the remote.
func (c *RepoCache) updateCredsAndFetch(bare BareRepo, clientOpts *ClientOptions) error {
	b, ok := bare.(*bareRepo)
	if !ok {
		return fmt.Errorf("unexpected bare repo type")
	}

	// Update credentials in case they've changed
	if clientOpts.Credentials != nil {
		b.creds = clientOpts.Credentials
		if err := b.setupAuth(b.homeDir); err != nil {
			return fmt.Errorf("error updating credentials: %w", err)
		}
	}

	// Fetch all refs
	cmd := b.buildGitCommand("fetch", "--prune", "origin", "+refs/heads/*:refs/heads/*", "+refs/tags/*:refs/tags/*")
	if _, err := libExec.Exec(cmd); err != nil {
		return fmt.Errorf("error fetching refs: %w", err)
	}
	return nil
}

// createWorkTreeRepo creates a Repo from a worktree of the cached bare repo.
// The returned Repo satisfies the same interface as git.Clone and can be used
// by existing selector code unchanged.
func (c *RepoCache) createWorkTreeRepo(bare BareRepo, cloneOpts *CloneOptions) (Repo, error) {
	b, ok := bare.(*bareRepo)
	if !ok {
		return nil, fmt.Errorf("unexpected bare repo type")
	}

	// Create a temp directory for the worktree
	wtDir, err := os.MkdirTemp(c.baseDir, "wt-")
	if err != nil {
		return nil, fmt.Errorf("error creating worktree temp dir: %w", err)
	}
	wtPath := filepath.Join(wtDir, "work")

	ref := cloneOpts.Branch
	if ref == "" {
		ref = "HEAD"
	}

	wt, err := bare.AddWorkTree(wtPath, &AddWorkTreeOptions{
		Ref: ref,
	})
	if err != nil {
		os.RemoveAll(wtDir) // nolint: errcheck
		return nil, fmt.Errorf("error adding worktree: %w", err)
	}

	// Wrap the worktree in a cachedWorkTreeRepo that implements Repo.
	// When closed, it removes the worktree from the bare repo and cleans up
	// the temp directory.
	return &cachedWorkTreeRepo{
		workTree: wt.(*workTree), // nolint: forcetypeassert
		bareRepo: b,
		wtDir:    wtDir,
	}, nil
}

// Len returns the number of entries currently in the cache.
func (c *RepoCache) Len() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return len(c.entries)
}

// Close cleans up all cached bare repos and their worktrees.
func (c *RepoCache) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	var firstErr error
	for key, entry := range c.entries {
		entry.mu.Lock()
		if entry.bare != nil {
			if err := entry.bare.Close(); err != nil && firstErr == nil {
				firstErr = fmt.Errorf("error closing cached repo %q: %w", key, err)
			}
		}
		entry.mu.Unlock()
		delete(c.entries, key)
	}
	return firstErr
}

// cachedWorkTreeRepo wraps a WorkTree to implement the Repo interface.
// It manages its own lifecycle: Close removes the worktree and cleans up
// the temporary directory.
type cachedWorkTreeRepo struct {
	*workTree
	bareRepo *bareRepo
	wtDir    string
}

func (r *cachedWorkTreeRepo) Close() error {
	// Remove the worktree from the bare repo's tracking
	if err := r.bareRepo.RemoveWorkTree(r.workTree.dir); err != nil {
		// If removal fails, still try to clean up the directory
		os.RemoveAll(r.wtDir) // nolint: errcheck
		return err
	}
	// Clean up the temp parent directory
	return os.RemoveAll(r.wtDir)
}

func (r *cachedWorkTreeRepo) Dir() string {
	return r.workTree.dir
}

func (r *cachedWorkTreeRepo) HomeDir() string {
	return r.workTree.homeDir
}

func (r *cachedWorkTreeRepo) URL() string {
	return r.workTree.originalURL
}
