/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the V1CSIVolumeSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1CSIVolumeSource{}

// V1CSIVolumeSource struct for V1CSIVolumeSource
type V1CSIVolumeSource struct {
	// driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
	Driver *string `json:"driver,omitempty"`
	// fsType to mount. Ex. \"ext4\", \"xfs\", \"ntfs\". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply. +optional
	FsType *string `json:"fsType,omitempty"`
	// nodePublishSecretRef is a reference to the secret object containing sensitive information to pass to the CSI driver to complete the CSI NodePublishVolume and NodeUnpublishVolume calls. This field is optional, and  may be empty if no secret is required. If the secret object contains more than one secret, all secret references are passed. +optional
	NodePublishSecretRef *V1LocalObjectReference `json:"nodePublishSecretRef,omitempty"`
	// readOnly specifies a read-only configuration for the volume. Defaults to false (read/write). +optional
	ReadOnly *bool `json:"readOnly,omitempty"`
	// volumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver's documentation for supported values. +optional
	VolumeAttributes *map[string]string `json:"volumeAttributes,omitempty"`
}

// NewV1CSIVolumeSource instantiates a new V1CSIVolumeSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1CSIVolumeSource() *V1CSIVolumeSource {
	this := V1CSIVolumeSource{}
	return &this
}

// NewV1CSIVolumeSourceWithDefaults instantiates a new V1CSIVolumeSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1CSIVolumeSourceWithDefaults() *V1CSIVolumeSource {
	this := V1CSIVolumeSource{}
	return &this
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *V1CSIVolumeSource) GetDriver() string {
	if o == nil || IsNil(o.Driver) {
		var ret string
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CSIVolumeSource) GetDriverOk() (*string, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *V1CSIVolumeSource) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given string and assigns it to the Driver field.
func (o *V1CSIVolumeSource) SetDriver(v string) {
	o.Driver = &v
}

// GetFsType returns the FsType field value if set, zero value otherwise.
func (o *V1CSIVolumeSource) GetFsType() string {
	if o == nil || IsNil(o.FsType) {
		var ret string
		return ret
	}
	return *o.FsType
}

// GetFsTypeOk returns a tuple with the FsType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CSIVolumeSource) GetFsTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FsType) {
		return nil, false
	}
	return o.FsType, true
}

// HasFsType returns a boolean if a field has been set.
func (o *V1CSIVolumeSource) HasFsType() bool {
	if o != nil && !IsNil(o.FsType) {
		return true
	}

	return false
}

// SetFsType gets a reference to the given string and assigns it to the FsType field.
func (o *V1CSIVolumeSource) SetFsType(v string) {
	o.FsType = &v
}

// GetNodePublishSecretRef returns the NodePublishSecretRef field value if set, zero value otherwise.
func (o *V1CSIVolumeSource) GetNodePublishSecretRef() V1LocalObjectReference {
	if o == nil || IsNil(o.NodePublishSecretRef) {
		var ret V1LocalObjectReference
		return ret
	}
	return *o.NodePublishSecretRef
}

// GetNodePublishSecretRefOk returns a tuple with the NodePublishSecretRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CSIVolumeSource) GetNodePublishSecretRefOk() (*V1LocalObjectReference, bool) {
	if o == nil || IsNil(o.NodePublishSecretRef) {
		return nil, false
	}
	return o.NodePublishSecretRef, true
}

// HasNodePublishSecretRef returns a boolean if a field has been set.
func (o *V1CSIVolumeSource) HasNodePublishSecretRef() bool {
	if o != nil && !IsNil(o.NodePublishSecretRef) {
		return true
	}

	return false
}

// SetNodePublishSecretRef gets a reference to the given V1LocalObjectReference and assigns it to the NodePublishSecretRef field.
func (o *V1CSIVolumeSource) SetNodePublishSecretRef(v V1LocalObjectReference) {
	o.NodePublishSecretRef = &v
}

// GetReadOnly returns the ReadOnly field value if set, zero value otherwise.
func (o *V1CSIVolumeSource) GetReadOnly() bool {
	if o == nil || IsNil(o.ReadOnly) {
		var ret bool
		return ret
	}
	return *o.ReadOnly
}

// GetReadOnlyOk returns a tuple with the ReadOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CSIVolumeSource) GetReadOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.ReadOnly) {
		return nil, false
	}
	return o.ReadOnly, true
}

// HasReadOnly returns a boolean if a field has been set.
func (o *V1CSIVolumeSource) HasReadOnly() bool {
	if o != nil && !IsNil(o.ReadOnly) {
		return true
	}

	return false
}

// SetReadOnly gets a reference to the given bool and assigns it to the ReadOnly field.
func (o *V1CSIVolumeSource) SetReadOnly(v bool) {
	o.ReadOnly = &v
}

// GetVolumeAttributes returns the VolumeAttributes field value if set, zero value otherwise.
func (o *V1CSIVolumeSource) GetVolumeAttributes() map[string]string {
	if o == nil || IsNil(o.VolumeAttributes) {
		var ret map[string]string
		return ret
	}
	return *o.VolumeAttributes
}

// GetVolumeAttributesOk returns a tuple with the VolumeAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1CSIVolumeSource) GetVolumeAttributesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.VolumeAttributes) {
		return nil, false
	}
	return o.VolumeAttributes, true
}

// HasVolumeAttributes returns a boolean if a field has been set.
func (o *V1CSIVolumeSource) HasVolumeAttributes() bool {
	if o != nil && !IsNil(o.VolumeAttributes) {
		return true
	}

	return false
}

// SetVolumeAttributes gets a reference to the given map[string]string and assigns it to the VolumeAttributes field.
func (o *V1CSIVolumeSource) SetVolumeAttributes(v map[string]string) {
	o.VolumeAttributes = &v
}

func (o V1CSIVolumeSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1CSIVolumeSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	if !IsNil(o.FsType) {
		toSerialize["fsType"] = o.FsType
	}
	if !IsNil(o.NodePublishSecretRef) {
		toSerialize["nodePublishSecretRef"] = o.NodePublishSecretRef
	}
	if !IsNil(o.ReadOnly) {
		toSerialize["readOnly"] = o.ReadOnly
	}
	if !IsNil(o.VolumeAttributes) {
		toSerialize["volumeAttributes"] = o.VolumeAttributes
	}
	return toSerialize, nil
}

type NullableV1CSIVolumeSource struct {
	value *V1CSIVolumeSource
	isSet bool
}

func (v NullableV1CSIVolumeSource) Get() *V1CSIVolumeSource {
	return v.value
}

func (v *NullableV1CSIVolumeSource) Set(val *V1CSIVolumeSource) {
	v.value = val
	v.isSet = true
}

func (v NullableV1CSIVolumeSource) IsSet() bool {
	return v.isSet
}

func (v *NullableV1CSIVolumeSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1CSIVolumeSource(val *V1CSIVolumeSource) *NullableV1CSIVolumeSource {
	return &NullableV1CSIVolumeSource{value: val, isSet: true}
}

func (v NullableV1CSIVolumeSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1CSIVolumeSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


