/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the UpdateConfigMapRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateConfigMapRequest{}

// UpdateConfigMapRequest struct for UpdateConfigMapRequest
type UpdateConfigMapRequest struct {
	Data *map[string]string `json:"data,omitempty"`
	Description *string `json:"description,omitempty"`
	Replicate *bool `json:"replicate,omitempty"`
}

// NewUpdateConfigMapRequest instantiates a new UpdateConfigMapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConfigMapRequest() *UpdateConfigMapRequest {
	this := UpdateConfigMapRequest{}
	return &this
}

// NewUpdateConfigMapRequestWithDefaults instantiates a new UpdateConfigMapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConfigMapRequestWithDefaults() *UpdateConfigMapRequest {
	this := UpdateConfigMapRequest{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateConfigMapRequest) GetData() map[string]string {
	if o == nil || IsNil(o.Data) {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfigMapRequest) GetDataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateConfigMapRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *UpdateConfigMapRequest) SetData(v map[string]string) {
	o.Data = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateConfigMapRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfigMapRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateConfigMapRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateConfigMapRequest) SetDescription(v string) {
	o.Description = &v
}

// GetReplicate returns the Replicate field value if set, zero value otherwise.
func (o *UpdateConfigMapRequest) GetReplicate() bool {
	if o == nil || IsNil(o.Replicate) {
		var ret bool
		return ret
	}
	return *o.Replicate
}

// GetReplicateOk returns a tuple with the Replicate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfigMapRequest) GetReplicateOk() (*bool, bool) {
	if o == nil || IsNil(o.Replicate) {
		return nil, false
	}
	return o.Replicate, true
}

// HasReplicate returns a boolean if a field has been set.
func (o *UpdateConfigMapRequest) HasReplicate() bool {
	if o != nil && !IsNil(o.Replicate) {
		return true
	}

	return false
}

// SetReplicate gets a reference to the given bool and assigns it to the Replicate field.
func (o *UpdateConfigMapRequest) SetReplicate(v bool) {
	o.Replicate = &v
}

func (o UpdateConfigMapRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateConfigMapRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Replicate) {
		toSerialize["replicate"] = o.Replicate
	}
	return toSerialize, nil
}

type NullableUpdateConfigMapRequest struct {
	value *UpdateConfigMapRequest
	isSet bool
}

func (v NullableUpdateConfigMapRequest) Get() *UpdateConfigMapRequest {
	return v.value
}

func (v *NullableUpdateConfigMapRequest) Set(val *UpdateConfigMapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConfigMapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConfigMapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConfigMapRequest(val *UpdateConfigMapRequest) *NullableUpdateConfigMapRequest {
	return &NullableUpdateConfigMapRequest{value: val, isSet: true}
}

func (v NullableUpdateConfigMapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConfigMapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


