/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the AnalysisRunMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnalysisRunMetadata{}

// AnalysisRunMetadata struct for AnalysisRunMetadata
type AnalysisRunMetadata struct {
	// Additional annotations to apply to an AnalysisRun.
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Additional labels to apply to an AnalysisRun.
	Labels *map[string]string `json:"labels,omitempty"`
}

// NewAnalysisRunMetadata instantiates a new AnalysisRunMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnalysisRunMetadata() *AnalysisRunMetadata {
	this := AnalysisRunMetadata{}
	return &this
}

// NewAnalysisRunMetadataWithDefaults instantiates a new AnalysisRunMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnalysisRunMetadataWithDefaults() *AnalysisRunMetadata {
	this := AnalysisRunMetadata{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *AnalysisRunMetadata) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisRunMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *AnalysisRunMetadata) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *AnalysisRunMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AnalysisRunMetadata) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AnalysisRunMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AnalysisRunMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *AnalysisRunMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

func (o AnalysisRunMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnalysisRunMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

type NullableAnalysisRunMetadata struct {
	value *AnalysisRunMetadata
	isSet bool
}

func (v NullableAnalysisRunMetadata) Get() *AnalysisRunMetadata {
	return v.value
}

func (v *NullableAnalysisRunMetadata) Set(val *AnalysisRunMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableAnalysisRunMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableAnalysisRunMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnalysisRunMetadata(val *AnalysisRunMetadata) *NullableAnalysisRunMetadata {
	return &NullableAnalysisRunMetadata{value: val, isSet: true}
}

func (v NullableAnalysisRunMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnalysisRunMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


