/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the RolloutsJobMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RolloutsJobMetric{}

// RolloutsJobMetric struct for RolloutsJobMetric
type RolloutsJobMetric struct {
	Metadata *V1ObjectMeta `json:"metadata,omitempty"`
	Spec *V1JobSpec `json:"spec,omitempty"`
}

// NewRolloutsJobMetric instantiates a new RolloutsJobMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRolloutsJobMetric() *RolloutsJobMetric {
	this := RolloutsJobMetric{}
	return &this
}

// NewRolloutsJobMetricWithDefaults instantiates a new RolloutsJobMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRolloutsJobMetricWithDefaults() *RolloutsJobMetric {
	this := RolloutsJobMetric{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *RolloutsJobMetric) GetMetadata() V1ObjectMeta {
	if o == nil || IsNil(o.Metadata) {
		var ret V1ObjectMeta
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RolloutsJobMetric) GetMetadataOk() (*V1ObjectMeta, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *RolloutsJobMetric) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V1ObjectMeta and assigns it to the Metadata field.
func (o *RolloutsJobMetric) SetMetadata(v V1ObjectMeta) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *RolloutsJobMetric) GetSpec() V1JobSpec {
	if o == nil || IsNil(o.Spec) {
		var ret V1JobSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RolloutsJobMetric) GetSpecOk() (*V1JobSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *RolloutsJobMetric) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given V1JobSpec and assigns it to the Spec field.
func (o *RolloutsJobMetric) SetSpec(v V1JobSpec) {
	o.Spec = &v
}

func (o RolloutsJobMetric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RolloutsJobMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableRolloutsJobMetric struct {
	value *RolloutsJobMetric
	isSet bool
}

func (v NullableRolloutsJobMetric) Get() *RolloutsJobMetric {
	return v.value
}

func (v *NullableRolloutsJobMetric) Set(val *RolloutsJobMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableRolloutsJobMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableRolloutsJobMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRolloutsJobMetric(val *RolloutsJobMetric) *NullableRolloutsJobMetric {
	return &NullableRolloutsJobMetric{value: val, isSet: true}
}

func (v NullableRolloutsJobMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRolloutsJobMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


