/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the V1PodDNSConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PodDNSConfig{}

// V1PodDNSConfig struct for V1PodDNSConfig
type V1PodDNSConfig struct {
	// A list of DNS name server IP addresses. This will be appended to the base nameservers generated from DNSPolicy. Duplicated nameservers will be removed. +optional +listType=atomic
	Nameservers []string `json:"nameservers,omitempty"`
	// A list of DNS resolver options. This will be merged with the base options generated from DNSPolicy. Duplicated entries will be removed. Resolution options given in Options will override those that appear in the base DNSPolicy. +optional +listType=atomic
	Options []V1PodDNSConfigOption `json:"options,omitempty"`
	// A list of DNS search domains for host-name lookup. This will be appended to the base search paths generated from DNSPolicy. Duplicated search paths will be removed. +optional +listType=atomic
	Searches []string `json:"searches,omitempty"`
}

// NewV1PodDNSConfig instantiates a new V1PodDNSConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PodDNSConfig() *V1PodDNSConfig {
	this := V1PodDNSConfig{}
	return &this
}

// NewV1PodDNSConfigWithDefaults instantiates a new V1PodDNSConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PodDNSConfigWithDefaults() *V1PodDNSConfig {
	this := V1PodDNSConfig{}
	return &this
}

// GetNameservers returns the Nameservers field value if set, zero value otherwise.
func (o *V1PodDNSConfig) GetNameservers() []string {
	if o == nil || IsNil(o.Nameservers) {
		var ret []string
		return ret
	}
	return o.Nameservers
}

// GetNameserversOk returns a tuple with the Nameservers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PodDNSConfig) GetNameserversOk() ([]string, bool) {
	if o == nil || IsNil(o.Nameservers) {
		return nil, false
	}
	return o.Nameservers, true
}

// HasNameservers returns a boolean if a field has been set.
func (o *V1PodDNSConfig) HasNameservers() bool {
	if o != nil && !IsNil(o.Nameservers) {
		return true
	}

	return false
}

// SetNameservers gets a reference to the given []string and assigns it to the Nameservers field.
func (o *V1PodDNSConfig) SetNameservers(v []string) {
	o.Nameservers = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *V1PodDNSConfig) GetOptions() []V1PodDNSConfigOption {
	if o == nil || IsNil(o.Options) {
		var ret []V1PodDNSConfigOption
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PodDNSConfig) GetOptionsOk() ([]V1PodDNSConfigOption, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *V1PodDNSConfig) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []V1PodDNSConfigOption and assigns it to the Options field.
func (o *V1PodDNSConfig) SetOptions(v []V1PodDNSConfigOption) {
	o.Options = v
}

// GetSearches returns the Searches field value if set, zero value otherwise.
func (o *V1PodDNSConfig) GetSearches() []string {
	if o == nil || IsNil(o.Searches) {
		var ret []string
		return ret
	}
	return o.Searches
}

// GetSearchesOk returns a tuple with the Searches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PodDNSConfig) GetSearchesOk() ([]string, bool) {
	if o == nil || IsNil(o.Searches) {
		return nil, false
	}
	return o.Searches, true
}

// HasSearches returns a boolean if a field has been set.
func (o *V1PodDNSConfig) HasSearches() bool {
	if o != nil && !IsNil(o.Searches) {
		return true
	}

	return false
}

// SetSearches gets a reference to the given []string and assigns it to the Searches field.
func (o *V1PodDNSConfig) SetSearches(v []string) {
	o.Searches = v
}

func (o V1PodDNSConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PodDNSConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nameservers) {
		toSerialize["nameservers"] = o.Nameservers
	}
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	if !IsNil(o.Searches) {
		toSerialize["searches"] = o.Searches
	}
	return toSerialize, nil
}

type NullableV1PodDNSConfig struct {
	value *V1PodDNSConfig
	isSet bool
}

func (v NullableV1PodDNSConfig) Get() *V1PodDNSConfig {
	return v.value
}

func (v *NullableV1PodDNSConfig) Set(val *V1PodDNSConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PodDNSConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PodDNSConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PodDNSConfig(val *V1PodDNSConfig) *NullableV1PodDNSConfig {
	return &NullableV1PodDNSConfig{value: val, isSet: true}
}

func (v NullableV1PodDNSConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PodDNSConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


