/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the UserClaims type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserClaims{}

// UserClaims struct for UserClaims
type UserClaims struct {
	Claims []Claim `json:"claims,omitempty"`
}

// NewUserClaims instantiates a new UserClaims object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserClaims() *UserClaims {
	this := UserClaims{}
	return &this
}

// NewUserClaimsWithDefaults instantiates a new UserClaims object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserClaimsWithDefaults() *UserClaims {
	this := UserClaims{}
	return &this
}

// GetClaims returns the Claims field value if set, zero value otherwise.
func (o *UserClaims) GetClaims() []Claim {
	if o == nil || IsNil(o.Claims) {
		var ret []Claim
		return ret
	}
	return o.Claims
}

// GetClaimsOk returns a tuple with the Claims field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserClaims) GetClaimsOk() ([]Claim, bool) {
	if o == nil || IsNil(o.Claims) {
		return nil, false
	}
	return o.Claims, true
}

// HasClaims returns a boolean if a field has been set.
func (o *UserClaims) HasClaims() bool {
	if o != nil && !IsNil(o.Claims) {
		return true
	}

	return false
}

// SetClaims gets a reference to the given []Claim and assigns it to the Claims field.
func (o *UserClaims) SetClaims(v []Claim) {
	o.Claims = v
}

func (o UserClaims) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserClaims) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Claims) {
		toSerialize["claims"] = o.Claims
	}
	return toSerialize, nil
}

type NullableUserClaims struct {
	value *UserClaims
	isSet bool
}

func (v NullableUserClaims) Get() *UserClaims {
	return v.value
}

func (v *NullableUserClaims) Set(val *UserClaims) {
	v.value = val
	v.isSet = true
}

func (v NullableUserClaims) IsSet() bool {
	return v.isSet
}

func (v *NullableUserClaims) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserClaims(val *UserClaims) *NullableUserClaims {
	return &NullableUserClaims{value: val, isSet: true}
}

func (v NullableUserClaims) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserClaims) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


