/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the DiscoveredImageReference type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoveredImageReference{}

// DiscoveredImageReference struct for DiscoveredImageReference
type DiscoveredImageReference struct {
	// Annotations is a map of key-value pairs that provide additional information about the image.
	Annotations *map[string]string `json:"annotations,omitempty"`
	// CreatedAt is the time the image was created. This field is optional, and not populated for every ImageSelectionStrategy.
	CreatedAt *string `json:"createdAt,omitempty"`
	// Digest is the digest of the image.  +kubebuilder:validation:MinLength=1 +kubebuilder:validation:Pattern=`^[a-z0-9]+:[a-f0-9]+$` +akuity:test-kubebuilder-pattern=Digest
	Digest *string `json:"digest,omitempty"`
	// Tag is the tag of the image.  +kubebuilder:validation:MinLength=1 +kubebuilder:validation:MaxLength=128 +kubebuilder:validation:Pattern=`^[\\w.\\-\\_]+$` +akuity:test-kubebuilder-pattern=Tag
	Tag *string `json:"tag,omitempty"`
}

// NewDiscoveredImageReference instantiates a new DiscoveredImageReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoveredImageReference() *DiscoveredImageReference {
	this := DiscoveredImageReference{}
	return &this
}

// NewDiscoveredImageReferenceWithDefaults instantiates a new DiscoveredImageReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoveredImageReferenceWithDefaults() *DiscoveredImageReference {
	this := DiscoveredImageReference{}
	return &this
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *DiscoveredImageReference) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredImageReference) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *DiscoveredImageReference) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *DiscoveredImageReference) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DiscoveredImageReference) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredImageReference) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DiscoveredImageReference) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *DiscoveredImageReference) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDigest returns the Digest field value if set, zero value otherwise.
func (o *DiscoveredImageReference) GetDigest() string {
	if o == nil || IsNil(o.Digest) {
		var ret string
		return ret
	}
	return *o.Digest
}

// GetDigestOk returns a tuple with the Digest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredImageReference) GetDigestOk() (*string, bool) {
	if o == nil || IsNil(o.Digest) {
		return nil, false
	}
	return o.Digest, true
}

// HasDigest returns a boolean if a field has been set.
func (o *DiscoveredImageReference) HasDigest() bool {
	if o != nil && !IsNil(o.Digest) {
		return true
	}

	return false
}

// SetDigest gets a reference to the given string and assigns it to the Digest field.
func (o *DiscoveredImageReference) SetDigest(v string) {
	o.Digest = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *DiscoveredImageReference) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredImageReference) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *DiscoveredImageReference) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *DiscoveredImageReference) SetTag(v string) {
	o.Tag = &v
}

func (o DiscoveredImageReference) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoveredImageReference) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Digest) {
		toSerialize["digest"] = o.Digest
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	return toSerialize, nil
}

type NullableDiscoveredImageReference struct {
	value *DiscoveredImageReference
	isSet bool
}

func (v NullableDiscoveredImageReference) Get() *DiscoveredImageReference {
	return v.value
}

func (v *NullableDiscoveredImageReference) Set(val *DiscoveredImageReference) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveredImageReference) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveredImageReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveredImageReference(val *DiscoveredImageReference) *NullableDiscoveredImageReference {
	return &NullableDiscoveredImageReference{value: val, isSet: true}
}

func (v NullableDiscoveredImageReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveredImageReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


