/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the CreateOrUpdateResourceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateResourceResponse{}

// CreateOrUpdateResourceResponse struct for CreateOrUpdateResourceResponse
type CreateOrUpdateResourceResponse struct {
	Results []CreateOrUpdateResourceResult `json:"results,omitempty"`
}

// NewCreateOrUpdateResourceResponse instantiates a new CreateOrUpdateResourceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateResourceResponse() *CreateOrUpdateResourceResponse {
	this := CreateOrUpdateResourceResponse{}
	return &this
}

// NewCreateOrUpdateResourceResponseWithDefaults instantiates a new CreateOrUpdateResourceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateResourceResponseWithDefaults() *CreateOrUpdateResourceResponse {
	this := CreateOrUpdateResourceResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CreateOrUpdateResourceResponse) GetResults() []CreateOrUpdateResourceResult {
	if o == nil || IsNil(o.Results) {
		var ret []CreateOrUpdateResourceResult
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateResourceResponse) GetResultsOk() ([]CreateOrUpdateResourceResult, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CreateOrUpdateResourceResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CreateOrUpdateResourceResult and assigns it to the Results field.
func (o *CreateOrUpdateResourceResponse) SetResults(v []CreateOrUpdateResourceResult) {
	o.Results = v
}

func (o CreateOrUpdateResourceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateResourceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableCreateOrUpdateResourceResponse struct {
	value *CreateOrUpdateResourceResponse
	isSet bool
}

func (v NullableCreateOrUpdateResourceResponse) Get() *CreateOrUpdateResourceResponse {
	return v.value
}

func (v *NullableCreateOrUpdateResourceResponse) Set(val *CreateOrUpdateResourceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateResourceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateResourceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateResourceResponse(val *CreateOrUpdateResourceResponse) *NullableCreateOrUpdateResourceResponse {
	return &NullableCreateOrUpdateResourceResponse{value: val, isSet: true}
}

func (v NullableCreateOrUpdateResourceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateResourceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


