/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AzureWebhookReceiverConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AzureWebhookReceiverConfig{}

// AzureWebhookReceiverConfig struct for AzureWebhookReceiverConfig
type AzureWebhookReceiverConfig struct {
	// SecretRef contains a reference to a Secret. For Project-scoped webhook receivers, the referenced Secret must be in the same namespace as the ProjectConfig.  For cluster-scoped webhook receivers, the referenced Secret must be in the designated \"system resources\" namespace.  The Secret's data map is expected to contain a `secret` key whose value does NOT need to be shared directly with Azure when registering a webhook. It is used only by Kargo to create a complex, hard-to-guess URL, which implicitly serves as a shared secret. For more information about Azure webhooks, please refer to the Azure documentation:   Azure Container Registry:  https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repositories   Azure DevOps:  http://learn.microsoft.com/en-us/azure/devops/service-hooks/services/webhooks?view=azure-devops  +kubebuilder:validation:Required
	SecretRef V1LocalObjectReference `json:"secretRef"`
}

type _AzureWebhookReceiverConfig AzureWebhookReceiverConfig

// NewAzureWebhookReceiverConfig instantiates a new AzureWebhookReceiverConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAzureWebhookReceiverConfig(secretRef V1LocalObjectReference) *AzureWebhookReceiverConfig {
	this := AzureWebhookReceiverConfig{}
	this.SecretRef = secretRef
	return &this
}

// NewAzureWebhookReceiverConfigWithDefaults instantiates a new AzureWebhookReceiverConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAzureWebhookReceiverConfigWithDefaults() *AzureWebhookReceiverConfig {
	this := AzureWebhookReceiverConfig{}
	return &this
}

// GetSecretRef returns the SecretRef field value
func (o *AzureWebhookReceiverConfig) GetSecretRef() V1LocalObjectReference {
	if o == nil {
		var ret V1LocalObjectReference
		return ret
	}

	return o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value
// and a boolean to check if the value has been set.
func (o *AzureWebhookReceiverConfig) GetSecretRefOk() (*V1LocalObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretRef, true
}

// SetSecretRef sets field value
func (o *AzureWebhookReceiverConfig) SetSecretRef(v V1LocalObjectReference) {
	o.SecretRef = v
}

func (o AzureWebhookReceiverConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AzureWebhookReceiverConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secretRef"] = o.SecretRef
	return toSerialize, nil
}

func (o *AzureWebhookReceiverConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secretRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAzureWebhookReceiverConfig := _AzureWebhookReceiverConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAzureWebhookReceiverConfig)

	if err != nil {
		return err
	}

	*o = AzureWebhookReceiverConfig(varAzureWebhookReceiverConfig)

	return err
}

type NullableAzureWebhookReceiverConfig struct {
	value *AzureWebhookReceiverConfig
	isSet bool
}

func (v NullableAzureWebhookReceiverConfig) Get() *AzureWebhookReceiverConfig {
	return v.value
}

func (v *NullableAzureWebhookReceiverConfig) Set(val *AzureWebhookReceiverConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAzureWebhookReceiverConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAzureWebhookReceiverConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAzureWebhookReceiverConfig(val *AzureWebhookReceiverConfig) *NullableAzureWebhookReceiverConfig {
	return &NullableAzureWebhookReceiverConfig{value: val, isSet: true}
}

func (v NullableAzureWebhookReceiverConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAzureWebhookReceiverConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


