/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the V1PodReadinessGate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PodReadinessGate{}

// V1PodReadinessGate struct for V1PodReadinessGate
type V1PodReadinessGate struct {
	// ConditionType refers to a condition in the pod's condition list with matching type.
	ConditionType *string `json:"conditionType,omitempty"`
}

// NewV1PodReadinessGate instantiates a new V1PodReadinessGate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PodReadinessGate() *V1PodReadinessGate {
	this := V1PodReadinessGate{}
	return &this
}

// NewV1PodReadinessGateWithDefaults instantiates a new V1PodReadinessGate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PodReadinessGateWithDefaults() *V1PodReadinessGate {
	this := V1PodReadinessGate{}
	return &this
}

// GetConditionType returns the ConditionType field value if set, zero value otherwise.
func (o *V1PodReadinessGate) GetConditionType() string {
	if o == nil || IsNil(o.ConditionType) {
		var ret string
		return ret
	}
	return *o.ConditionType
}

// GetConditionTypeOk returns a tuple with the ConditionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1PodReadinessGate) GetConditionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ConditionType) {
		return nil, false
	}
	return o.ConditionType, true
}

// HasConditionType returns a boolean if a field has been set.
func (o *V1PodReadinessGate) HasConditionType() bool {
	if o != nil && !IsNil(o.ConditionType) {
		return true
	}

	return false
}

// SetConditionType gets a reference to the given string and assigns it to the ConditionType field.
func (o *V1PodReadinessGate) SetConditionType(v string) {
	o.ConditionType = &v
}

func (o V1PodReadinessGate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PodReadinessGate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConditionType) {
		toSerialize["conditionType"] = o.ConditionType
	}
	return toSerialize, nil
}

type NullableV1PodReadinessGate struct {
	value *V1PodReadinessGate
	isSet bool
}

func (v NullableV1PodReadinessGate) Get() *V1PodReadinessGate {
	return v.value
}

func (v *NullableV1PodReadinessGate) Set(val *V1PodReadinessGate) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PodReadinessGate) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PodReadinessGate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PodReadinessGate(val *V1PodReadinessGate) *NullableV1PodReadinessGate {
	return &NullableV1PodReadinessGate{value: val, isSet: true}
}

func (v NullableV1PodReadinessGate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PodReadinessGate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


