/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the GitCommit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GitCommit{}

// GitCommit struct for GitCommit
type GitCommit struct {
	// Author is the author of the commit.
	Author *string `json:"author,omitempty"`
	// Branch denotes the branch of the repository where this commit was found.
	Branch *string `json:"branch,omitempty"`
	// Committer is the person who committed the commit.
	Committer *string `json:"committer,omitempty"`
	// ID is the ID of a specific commit in the Git repository specified by RepoURL.
	Id *string `json:"id,omitempty"`
	// Message is the message associated with the commit. At present, this only contains the first line (subject) of the commit message.
	Message *string `json:"message,omitempty"`
	// RepoURL is the URL of a Git repository.
	RepoURL *string `json:"repoURL,omitempty"`
	// Tag denotes a tag in the repository that matched selection criteria and resolved to this commit.
	Tag *string `json:"tag,omitempty"`
}

// NewGitCommit instantiates a new GitCommit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGitCommit() *GitCommit {
	this := GitCommit{}
	return &this
}

// NewGitCommitWithDefaults instantiates a new GitCommit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGitCommitWithDefaults() *GitCommit {
	this := GitCommit{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *GitCommit) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *GitCommit) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *GitCommit) SetAuthor(v string) {
	o.Author = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *GitCommit) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *GitCommit) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *GitCommit) SetBranch(v string) {
	o.Branch = &v
}

// GetCommitter returns the Committer field value if set, zero value otherwise.
func (o *GitCommit) GetCommitter() string {
	if o == nil || IsNil(o.Committer) {
		var ret string
		return ret
	}
	return *o.Committer
}

// GetCommitterOk returns a tuple with the Committer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetCommitterOk() (*string, bool) {
	if o == nil || IsNil(o.Committer) {
		return nil, false
	}
	return o.Committer, true
}

// HasCommitter returns a boolean if a field has been set.
func (o *GitCommit) HasCommitter() bool {
	if o != nil && !IsNil(o.Committer) {
		return true
	}

	return false
}

// SetCommitter gets a reference to the given string and assigns it to the Committer field.
func (o *GitCommit) SetCommitter(v string) {
	o.Committer = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GitCommit) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GitCommit) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GitCommit) SetId(v string) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GitCommit) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GitCommit) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GitCommit) SetMessage(v string) {
	o.Message = &v
}

// GetRepoURL returns the RepoURL field value if set, zero value otherwise.
func (o *GitCommit) GetRepoURL() string {
	if o == nil || IsNil(o.RepoURL) {
		var ret string
		return ret
	}
	return *o.RepoURL
}

// GetRepoURLOk returns a tuple with the RepoURL field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetRepoURLOk() (*string, bool) {
	if o == nil || IsNil(o.RepoURL) {
		return nil, false
	}
	return o.RepoURL, true
}

// HasRepoURL returns a boolean if a field has been set.
func (o *GitCommit) HasRepoURL() bool {
	if o != nil && !IsNil(o.RepoURL) {
		return true
	}

	return false
}

// SetRepoURL gets a reference to the given string and assigns it to the RepoURL field.
func (o *GitCommit) SetRepoURL(v string) {
	o.RepoURL = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *GitCommit) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GitCommit) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *GitCommit) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *GitCommit) SetTag(v string) {
	o.Tag = &v
}

func (o GitCommit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GitCommit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Committer) {
		toSerialize["committer"] = o.Committer
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.RepoURL) {
		toSerialize["repoURL"] = o.RepoURL
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	return toSerialize, nil
}

type NullableGitCommit struct {
	value *GitCommit
	isSet bool
}

func (v NullableGitCommit) Get() *GitCommit {
	return v.value
}

func (v *NullableGitCommit) Set(val *GitCommit) {
	v.value = val
	v.isSet = true
}

func (v NullableGitCommit) IsSet() bool {
	return v.isSet
}

func (v *NullableGitCommit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGitCommit(val *GitCommit) *NullableGitCommit {
	return &NullableGitCommit{value: val, isSet: true}
}

func (v NullableGitCommit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGitCommit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


