/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the PromotionTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromotionTemplate{}

// PromotionTemplate struct for PromotionTemplate
type PromotionTemplate struct {
	Spec *PromotionTemplateSpec `json:"spec,omitempty"`
}

// NewPromotionTemplate instantiates a new PromotionTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionTemplate() *PromotionTemplate {
	this := PromotionTemplate{}
	return &this
}

// NewPromotionTemplateWithDefaults instantiates a new PromotionTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionTemplateWithDefaults() *PromotionTemplate {
	this := PromotionTemplate{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *PromotionTemplate) GetSpec() PromotionTemplateSpec {
	if o == nil || IsNil(o.Spec) {
		var ret PromotionTemplateSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionTemplate) GetSpecOk() (*PromotionTemplateSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *PromotionTemplate) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given PromotionTemplateSpec and assigns it to the Spec field.
func (o *PromotionTemplate) SetSpec(v PromotionTemplateSpec) {
	o.Spec = &v
}

func (o PromotionTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromotionTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullablePromotionTemplate struct {
	value *PromotionTemplate
	isSet bool
}

func (v NullablePromotionTemplate) Get() *PromotionTemplate {
	return v.value
}

func (v *NullablePromotionTemplate) Set(val *PromotionTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionTemplate(val *PromotionTemplate) *NullablePromotionTemplate {
	return &NullablePromotionTemplate{value: val, isSet: true}
}

func (v NullablePromotionTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


