/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the PromoteToStageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromoteToStageRequest{}

// PromoteToStageRequest struct for PromoteToStageRequest
type PromoteToStageRequest struct {
	Freight *string `json:"freight,omitempty"`
	FreightAlias *string `json:"freightAlias,omitempty"`
	// Origin is the canonical Freight origin key (e.g. \"Warehouse/foo\"). When set, the promotion webhook resolves it to the current auto-promotion candidate. Exactly one of Freight, FreightAlias, or Origin must be set.
	Origin *string `json:"origin,omitempty"`
}

// NewPromoteToStageRequest instantiates a new PromoteToStageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromoteToStageRequest() *PromoteToStageRequest {
	this := PromoteToStageRequest{}
	return &this
}

// NewPromoteToStageRequestWithDefaults instantiates a new PromoteToStageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromoteToStageRequestWithDefaults() *PromoteToStageRequest {
	this := PromoteToStageRequest{}
	return &this
}

// GetFreight returns the Freight field value if set, zero value otherwise.
func (o *PromoteToStageRequest) GetFreight() string {
	if o == nil || IsNil(o.Freight) {
		var ret string
		return ret
	}
	return *o.Freight
}

// GetFreightOk returns a tuple with the Freight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteToStageRequest) GetFreightOk() (*string, bool) {
	if o == nil || IsNil(o.Freight) {
		return nil, false
	}
	return o.Freight, true
}

// HasFreight returns a boolean if a field has been set.
func (o *PromoteToStageRequest) HasFreight() bool {
	if o != nil && !IsNil(o.Freight) {
		return true
	}

	return false
}

// SetFreight gets a reference to the given string and assigns it to the Freight field.
func (o *PromoteToStageRequest) SetFreight(v string) {
	o.Freight = &v
}

// GetFreightAlias returns the FreightAlias field value if set, zero value otherwise.
func (o *PromoteToStageRequest) GetFreightAlias() string {
	if o == nil || IsNil(o.FreightAlias) {
		var ret string
		return ret
	}
	return *o.FreightAlias
}

// GetFreightAliasOk returns a tuple with the FreightAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteToStageRequest) GetFreightAliasOk() (*string, bool) {
	if o == nil || IsNil(o.FreightAlias) {
		return nil, false
	}
	return o.FreightAlias, true
}

// HasFreightAlias returns a boolean if a field has been set.
func (o *PromoteToStageRequest) HasFreightAlias() bool {
	if o != nil && !IsNil(o.FreightAlias) {
		return true
	}

	return false
}

// SetFreightAlias gets a reference to the given string and assigns it to the FreightAlias field.
func (o *PromoteToStageRequest) SetFreightAlias(v string) {
	o.FreightAlias = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *PromoteToStageRequest) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromoteToStageRequest) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *PromoteToStageRequest) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *PromoteToStageRequest) SetOrigin(v string) {
	o.Origin = &v
}

func (o PromoteToStageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromoteToStageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Freight) {
		toSerialize["freight"] = o.Freight
	}
	if !IsNil(o.FreightAlias) {
		toSerialize["freightAlias"] = o.FreightAlias
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	return toSerialize, nil
}

type NullablePromoteToStageRequest struct {
	value *PromoteToStageRequest
	isSet bool
}

func (v NullablePromoteToStageRequest) Get() *PromoteToStageRequest {
	return v.value
}

func (v *NullablePromoteToStageRequest) Set(val *PromoteToStageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePromoteToStageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePromoteToStageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromoteToStageRequest(val *PromoteToStageRequest) *NullablePromoteToStageRequest {
	return &NullablePromoteToStageRequest{value: val, isSet: true}
}

func (v NullablePromoteToStageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromoteToStageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


