/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the HealthCheckStep type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthCheckStep{}

// HealthCheckStep struct for HealthCheckStep
type HealthCheckStep struct {
	// Config is the configuration for the directive.
	Config interface{} `json:"config,omitempty"`
	// Uses identifies a runner that can execute this step.  +kubebuilder:validation:MinLength=1
	Uses *string `json:"uses,omitempty"`
}

// NewHealthCheckStep instantiates a new HealthCheckStep object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckStep() *HealthCheckStep {
	this := HealthCheckStep{}
	return &this
}

// NewHealthCheckStepWithDefaults instantiates a new HealthCheckStep object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckStepWithDefaults() *HealthCheckStep {
	this := HealthCheckStep{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *HealthCheckStep) GetConfig() interface{} {
	if o == nil || IsNil(o.Config) {
		var ret interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheckStep) GetConfigOk() (interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *HealthCheckStep) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given interface{} and assigns it to the Config field.
func (o *HealthCheckStep) SetConfig(v interface{}) {
	o.Config = v
}

// GetUses returns the Uses field value if set, zero value otherwise.
func (o *HealthCheckStep) GetUses() string {
	if o == nil || IsNil(o.Uses) {
		var ret string
		return ret
	}
	return *o.Uses
}

// GetUsesOk returns a tuple with the Uses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthCheckStep) GetUsesOk() (*string, bool) {
	if o == nil || IsNil(o.Uses) {
		return nil, false
	}
	return o.Uses, true
}

// HasUses returns a boolean if a field has been set.
func (o *HealthCheckStep) HasUses() bool {
	if o != nil && !IsNil(o.Uses) {
		return true
	}

	return false
}

// SetUses gets a reference to the given string and assigns it to the Uses field.
func (o *HealthCheckStep) SetUses(v string) {
	o.Uses = &v
}

func (o HealthCheckStep) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthCheckStep) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Uses) {
		toSerialize["uses"] = o.Uses
	}
	return toSerialize, nil
}

type NullableHealthCheckStep struct {
	value *HealthCheckStep
	isSet bool
}

func (v NullableHealthCheckStep) Get() *HealthCheckStep {
	return v.value
}

func (v *NullableHealthCheckStep) Set(val *HealthCheckStep) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckStep) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckStep) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckStep(val *HealthCheckStep) *NullableHealthCheckStep {
	return &NullableHealthCheckStep{value: val, isSet: true}
}

func (v NullableHealthCheckStep) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckStep) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


