/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the PromotionPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PromotionPolicy{}

// PromotionPolicy struct for PromotionPolicy
type PromotionPolicy struct {
	// AutoPromotionEnabled indicates whether new Freight can automatically be promoted into the Stage referenced by the Stage field. Note: There are may be other conditions also required for an auto-promotion to occur. This field defaults to false, but is commonly set to true for Stages that subscribe to Warehouses instead of other, upstream Stages. This allows users to define Stages that are automatically updated as soon as new artifacts are detected.
	AutoPromotionEnabled *bool `json:"autoPromotionEnabled,omitempty"`
	// AutoRollback describes the conditions under which this Stage should automatically roll back to the last known-good (verified) Freight. When nil, auto-rollback is disabled.  Kargo Enterprise only: This field is ignored in Kargo OSS.
	AutoRollback *AutoRollbackConfig `json:"autoRollback,omitempty"`
	// Stage is the name of the Stage to which this policy applies.  Deprecated: Use StageSelector instead.  +kubebuilder:validation:Pattern=^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
	Stage *string `json:"stage,omitempty"`
	// StageSelector is a selector that matches the Stage resource to which this policy applies.
	StageSelector *PromotionPolicySelector `json:"stageSelector,omitempty"`
}

// NewPromotionPolicy instantiates a new PromotionPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPromotionPolicy() *PromotionPolicy {
	this := PromotionPolicy{}
	return &this
}

// NewPromotionPolicyWithDefaults instantiates a new PromotionPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPromotionPolicyWithDefaults() *PromotionPolicy {
	this := PromotionPolicy{}
	return &this
}

// GetAutoPromotionEnabled returns the AutoPromotionEnabled field value if set, zero value otherwise.
func (o *PromotionPolicy) GetAutoPromotionEnabled() bool {
	if o == nil || IsNil(o.AutoPromotionEnabled) {
		var ret bool
		return ret
	}
	return *o.AutoPromotionEnabled
}

// GetAutoPromotionEnabledOk returns a tuple with the AutoPromotionEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionPolicy) GetAutoPromotionEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoPromotionEnabled) {
		return nil, false
	}
	return o.AutoPromotionEnabled, true
}

// HasAutoPromotionEnabled returns a boolean if a field has been set.
func (o *PromotionPolicy) HasAutoPromotionEnabled() bool {
	if o != nil && !IsNil(o.AutoPromotionEnabled) {
		return true
	}

	return false
}

// SetAutoPromotionEnabled gets a reference to the given bool and assigns it to the AutoPromotionEnabled field.
func (o *PromotionPolicy) SetAutoPromotionEnabled(v bool) {
	o.AutoPromotionEnabled = &v
}

// GetAutoRollback returns the AutoRollback field value if set, zero value otherwise.
func (o *PromotionPolicy) GetAutoRollback() AutoRollbackConfig {
	if o == nil || IsNil(o.AutoRollback) {
		var ret AutoRollbackConfig
		return ret
	}
	return *o.AutoRollback
}

// GetAutoRollbackOk returns a tuple with the AutoRollback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionPolicy) GetAutoRollbackOk() (*AutoRollbackConfig, bool) {
	if o == nil || IsNil(o.AutoRollback) {
		return nil, false
	}
	return o.AutoRollback, true
}

// HasAutoRollback returns a boolean if a field has been set.
func (o *PromotionPolicy) HasAutoRollback() bool {
	if o != nil && !IsNil(o.AutoRollback) {
		return true
	}

	return false
}

// SetAutoRollback gets a reference to the given AutoRollbackConfig and assigns it to the AutoRollback field.
func (o *PromotionPolicy) SetAutoRollback(v AutoRollbackConfig) {
	o.AutoRollback = &v
}

// GetStage returns the Stage field value if set, zero value otherwise.
func (o *PromotionPolicy) GetStage() string {
	if o == nil || IsNil(o.Stage) {
		var ret string
		return ret
	}
	return *o.Stage
}

// GetStageOk returns a tuple with the Stage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionPolicy) GetStageOk() (*string, bool) {
	if o == nil || IsNil(o.Stage) {
		return nil, false
	}
	return o.Stage, true
}

// HasStage returns a boolean if a field has been set.
func (o *PromotionPolicy) HasStage() bool {
	if o != nil && !IsNil(o.Stage) {
		return true
	}

	return false
}

// SetStage gets a reference to the given string and assigns it to the Stage field.
func (o *PromotionPolicy) SetStage(v string) {
	o.Stage = &v
}

// GetStageSelector returns the StageSelector field value if set, zero value otherwise.
func (o *PromotionPolicy) GetStageSelector() PromotionPolicySelector {
	if o == nil || IsNil(o.StageSelector) {
		var ret PromotionPolicySelector
		return ret
	}
	return *o.StageSelector
}

// GetStageSelectorOk returns a tuple with the StageSelector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PromotionPolicy) GetStageSelectorOk() (*PromotionPolicySelector, bool) {
	if o == nil || IsNil(o.StageSelector) {
		return nil, false
	}
	return o.StageSelector, true
}

// HasStageSelector returns a boolean if a field has been set.
func (o *PromotionPolicy) HasStageSelector() bool {
	if o != nil && !IsNil(o.StageSelector) {
		return true
	}

	return false
}

// SetStageSelector gets a reference to the given PromotionPolicySelector and assigns it to the StageSelector field.
func (o *PromotionPolicy) SetStageSelector(v PromotionPolicySelector) {
	o.StageSelector = &v
}

func (o PromotionPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PromotionPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutoPromotionEnabled) {
		toSerialize["autoPromotionEnabled"] = o.AutoPromotionEnabled
	}
	if !IsNil(o.AutoRollback) {
		toSerialize["autoRollback"] = o.AutoRollback
	}
	if !IsNil(o.Stage) {
		toSerialize["stage"] = o.Stage
	}
	if !IsNil(o.StageSelector) {
		toSerialize["stageSelector"] = o.StageSelector
	}
	return toSerialize, nil
}

type NullablePromotionPolicy struct {
	value *PromotionPolicy
	isSet bool
}

func (v NullablePromotionPolicy) Get() *PromotionPolicy {
	return v.value
}

func (v *NullablePromotionPolicy) Set(val *PromotionPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullablePromotionPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullablePromotionPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePromotionPolicy(val *PromotionPolicy) *NullablePromotionPolicy {
	return &NullablePromotionPolicy{value: val, isSet: true}
}

func (v NullablePromotionPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePromotionPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


