/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
)

// checks if the V1HostAlias type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1HostAlias{}

// V1HostAlias struct for V1HostAlias
type V1HostAlias struct {
	// Hostnames for the above IP address. +listType=atomic
	Hostnames []string `json:"hostnames,omitempty"`
	// IP address of the host file entry. +required
	Ip *string `json:"ip,omitempty"`
}

// NewV1HostAlias instantiates a new V1HostAlias object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1HostAlias() *V1HostAlias {
	this := V1HostAlias{}
	return &this
}

// NewV1HostAliasWithDefaults instantiates a new V1HostAlias object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1HostAliasWithDefaults() *V1HostAlias {
	this := V1HostAlias{}
	return &this
}

// GetHostnames returns the Hostnames field value if set, zero value otherwise.
func (o *V1HostAlias) GetHostnames() []string {
	if o == nil || IsNil(o.Hostnames) {
		var ret []string
		return ret
	}
	return o.Hostnames
}

// GetHostnamesOk returns a tuple with the Hostnames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1HostAlias) GetHostnamesOk() ([]string, bool) {
	if o == nil || IsNil(o.Hostnames) {
		return nil, false
	}
	return o.Hostnames, true
}

// HasHostnames returns a boolean if a field has been set.
func (o *V1HostAlias) HasHostnames() bool {
	if o != nil && !IsNil(o.Hostnames) {
		return true
	}

	return false
}

// SetHostnames gets a reference to the given []string and assigns it to the Hostnames field.
func (o *V1HostAlias) SetHostnames(v []string) {
	o.Hostnames = v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *V1HostAlias) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1HostAlias) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *V1HostAlias) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *V1HostAlias) SetIp(v string) {
	o.Ip = &v
}

func (o V1HostAlias) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1HostAlias) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hostnames) {
		toSerialize["hostnames"] = o.Hostnames
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	return toSerialize, nil
}

type NullableV1HostAlias struct {
	value *V1HostAlias
	isSet bool
}

func (v NullableV1HostAlias) Get() *V1HostAlias {
	return v.value
}

func (v *NullableV1HostAlias) Set(val *V1HostAlias) {
	v.value = val
	v.isSet = true
}

func (v NullableV1HostAlias) IsSet() bool {
	return v.isSet
}

func (v *NullableV1HostAlias) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1HostAlias(val *V1HostAlias) *NullableV1HostAlias {
	return &NullableV1HostAlias{value: val, isSet: true}
}

func (v NullableV1HostAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1HostAlias) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


