/*
Kargo API

REST API for Kargo

API version: v1alpha1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package generatedv2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GiteaWebhookReceiverConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GiteaWebhookReceiverConfig{}

// GiteaWebhookReceiverConfig struct for GiteaWebhookReceiverConfig
type GiteaWebhookReceiverConfig struct {
	// SecretRef contains a reference to a Secret. For Project-scoped webhook receivers, the referenced Secret must be in the same namespace as the ProjectConfig.  For cluster-scoped webhook receivers, the referenced Secret must be in the designated \"system resources\" namespace.  The Secret's data map is expected to contain a `secret` key whose value is the shared secret used to authenticate the webhook requests sent by Gitea. For more information please refer to the Gitea documentation:   https://docs.gitea.io/en-us/webhooks/  +kubebuilder:validation:Required
	SecretRef V1LocalObjectReference `json:"secretRef"`
}

type _GiteaWebhookReceiverConfig GiteaWebhookReceiverConfig

// NewGiteaWebhookReceiverConfig instantiates a new GiteaWebhookReceiverConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGiteaWebhookReceiverConfig(secretRef V1LocalObjectReference) *GiteaWebhookReceiverConfig {
	this := GiteaWebhookReceiverConfig{}
	this.SecretRef = secretRef
	return &this
}

// NewGiteaWebhookReceiverConfigWithDefaults instantiates a new GiteaWebhookReceiverConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGiteaWebhookReceiverConfigWithDefaults() *GiteaWebhookReceiverConfig {
	this := GiteaWebhookReceiverConfig{}
	return &this
}

// GetSecretRef returns the SecretRef field value
func (o *GiteaWebhookReceiverConfig) GetSecretRef() V1LocalObjectReference {
	if o == nil {
		var ret V1LocalObjectReference
		return ret
	}

	return o.SecretRef
}

// GetSecretRefOk returns a tuple with the SecretRef field value
// and a boolean to check if the value has been set.
func (o *GiteaWebhookReceiverConfig) GetSecretRefOk() (*V1LocalObjectReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretRef, true
}

// SetSecretRef sets field value
func (o *GiteaWebhookReceiverConfig) SetSecretRef(v V1LocalObjectReference) {
	o.SecretRef = v
}

func (o GiteaWebhookReceiverConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GiteaWebhookReceiverConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secretRef"] = o.SecretRef
	return toSerialize, nil
}

func (o *GiteaWebhookReceiverConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secretRef",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGiteaWebhookReceiverConfig := _GiteaWebhookReceiverConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGiteaWebhookReceiverConfig)

	if err != nil {
		return err
	}

	*o = GiteaWebhookReceiverConfig(varGiteaWebhookReceiverConfig)

	return err
}

type NullableGiteaWebhookReceiverConfig struct {
	value *GiteaWebhookReceiverConfig
	isSet bool
}

func (v NullableGiteaWebhookReceiverConfig) Get() *GiteaWebhookReceiverConfig {
	return v.value
}

func (v *NullableGiteaWebhookReceiverConfig) Set(val *GiteaWebhookReceiverConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableGiteaWebhookReceiverConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableGiteaWebhookReceiverConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGiteaWebhookReceiverConfig(val *GiteaWebhookReceiverConfig) *NullableGiteaWebhookReceiverConfig {
	return &NullableGiteaWebhookReceiverConfig{value: val, isSet: true}
}

func (v NullableGiteaWebhookReceiverConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGiteaWebhookReceiverConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


