apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-cluster-secrets-reader
  namespace: {{ .Values.global.clusterSecretsNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-cluster-secrets-reader
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-controller
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: kargo-external-webhooks-server
