apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-cluster-secrets-reader
  namespace: {{ .Values.global.clusterSecretsNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-cluster-secrets-admin
  namespace: {{ .Values.global.clusterSecretsNamespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
