{{- if .Values.webhooksServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.kubernetesWebhooksServer.labels" . | nindent 4 }}
{{- end }}
