apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
name: k3d-kargo-dev-cluster
product: k3d
registry: kargo-dev-registry
k3d:
  v1alpha4Simple:
    ports:
    - port: 30080:30080
      nodeFilters:
      - loadbalancer
