{{- if .Values.managementController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-management-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.managementController.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.labels) .Values.managementController.serviceAccount.labels) }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) .Values.managementController.serviceAccount.annotations) }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
