{{- if .Values.managementController.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-management-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.managementController.labels" . | nindent 4 }}
{{- end }}
