{{- include "kargo.database.validate" . }}
{{- if and .Values.workloads.install .Values.database.postgres.enabled (not .Values.database.postgres.existingSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.componentLabels" (dict "root" . "labels" .Values.database.postgres.labels) | nindent 4 }}
    {{- include "kargo.postgres.labels" . | nindent 4 }}
  {{- include "kargo.annotations" (dict "root" . "annotations" .Values.database.postgres.annotations) | nindent 2 }}
stringData:
  password: {{ include "kargo.postgres.password" . | quote }}
{{- end }}
