{{- include "kargo.database.validate" . }}
{{- if and .Values.workloads.install .Values.database.postgres.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kargo-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.postgres.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.labels) .Values.database.postgres.serviceAccount.labels) }}
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  {{- with (mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) .Values.database.postgres.serviceAccount.annotations) }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
