apiVersion: v1
kind: Service
metadata:
  name: {{ include "kargo.fullname" . }}-webhook-server
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "kargo.selectorLabels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
