{{- if .Values.controller.webhooks.register }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "kargo.fullname" . }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kargo.fullname" . }}-webhook-server
webhooks:
- name: environment.kargo.akuity.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "kargo.fullname" . }}-webhook-server
      path: /mutate-kargo-akuity-io-v1alpha1-environment
  rules:
  - scope: Namespaced
    apiGroups: ["kargo.akuity.io"]
    apiVersions: ["v1alpha1"]
    resources: ["environments"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kargo.fullname" . }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.controller.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kargo.fullname" . }}-webhook-server
webhooks:
- name: environment.kargo.akuity.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "kargo.fullname" . }}-webhook-server
      path: /validate-kargo-akuity-io-v1alpha1-environment
  rules:
  - scope: Namespaced
    apiGroups: ["kargo.akuity.io"]
    apiVersions: ["v1alpha1"]
    resources: ["environments"]
    operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
{{- end }}
