{{- if and .Values.bookkeeper.server.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8sta.bookkeeper.server.fullname" . }}
  labels:
    {{- include "k8sta.labels" . | nindent 4 }}
    {{- include "k8sta.bookkeeper.server.labels" . | nindent 4 }}
{{- end }}
