apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: auto-hold
  namespace: auto-promotion-hold
spec:
  freightCreationPolicy: Manual
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      discoveryLimit: 3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: auto-hold-api
  namespace: auto-promotion-hold
spec:
  freightCreationPolicy: Manual
  subscriptions:
  - image:
      repoURL: public.ecr.aws/docker/library/redis
      discoveryLimit: 2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: 39f8209d87b5222d5dbebf5e6f1d9a54fe7d7b52
  namespace: auto-promotion-hold
alias: frontend-v001
origin:
  kind: Warehouse
  name: auto-hold
images:
- repoURL: public.ecr.aws/nginx/nginx
  tag: 1.26.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: 7d96255278537d99b0c35445c3da426147d990bf
  namespace: auto-promotion-hold
alias: frontend-v002
origin:
  kind: Warehouse
  name: auto-hold
images:
- repoURL: public.ecr.aws/nginx/nginx
  tag: 1.26.1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: 3966bf28d5d67698bfd4816aecafd66d96a4226c
  namespace: auto-promotion-hold
alias: frontend-v003
origin:
  kind: Warehouse
  name: auto-hold
images:
- repoURL: public.ecr.aws/nginx/nginx
  tag: 1.26.2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: 10e608d617ce292f14398c07bcfadedd27b1ae6c
  namespace: auto-promotion-hold
alias: api-v001
origin:
  kind: Warehouse
  name: auto-hold-api
images:
- repoURL: public.ecr.aws/docker/library/redis
  tag: 7.2.4
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
metadata:
  name: d2f95df42a8f2ed206d7f4c15c5c5888454633eb
  namespace: auto-promotion-hold
alias: api-v002
origin:
  kind: Warehouse
  name: auto-hold-api
images:
- repoURL: public.ecr.aws/docker/library/redis
  tag: 7.2.5
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: single-origin-hold
  namespace: auto-promotion-hold
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: auto-hold
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
      - uses: http
        as: wait-10-seconds
        config:
          url: https://postman-echo.com/delay/10
          timeout: 30s
          responseContentType: application/json
          successExpression: response.status == 200 && response.body.delay == "10"
      - uses: set-metadata
        config:
          updates:
          - kind: Stage
            name: single-origin-hold
            values:
              manualTest: auto-promotion-hold
              lastStory: single-origin-hold
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: multi-origin-holds
  namespace: auto-promotion-hold
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: auto-hold
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  - origin:
      kind: Warehouse
      name: auto-hold-api
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
      - uses: set-metadata
        config:
          updates:
          - kind: Stage
            name: multi-origin-holds
            values:
              manualTest: auto-promotion-hold
              lastStory: multi-origin-holds
