apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: single-origin-hold
  namespace: auto-promotion-hold
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: auto-hold
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
      - uses: http
        as: wait-10-seconds
        config:
          url: https://postman-echo.com/delay/10
          timeout: 30s
          responseContentType: application/json
          successExpression: response.status == 200 && response.body.delay == "10"
      - uses: set-metadata
        config:
          updates:
          - kind: Stage
            name: single-origin-hold
            values:
              manualTest: auto-promotion-hold
              lastStory: single-origin-hold
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: multi-origin-holds
  namespace: auto-promotion-hold
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: auto-hold
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  - origin:
      kind: Warehouse
      name: auto-hold-api
    sources:
      direct: true
      autoPromotionOptions:
        selectionPolicy: NewestFreight
  promotionTemplate:
    spec:
      steps:
      - uses: set-metadata
        config:
          updates:
          - kind: Stage
            name: multi-origin-holds
            values:
              manualTest: auto-promotion-hold
              lastStory: multi-origin-holds
