apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: auto-hold
  namespace: auto-promotion-hold
spec:
  freightCreationPolicy: Manual
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      discoveryLimit: 3
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: auto-hold-api
  namespace: auto-promotion-hold
spec:
  freightCreationPolicy: Manual
  subscriptions:
  - image:
      repoURL: public.ecr.aws/docker/library/redis
      discoveryLimit: 2
