{{- if and .Values.externalWebhooksServer.enabled .Values.externalWebhooksServer.tls.enabled .Values.externalWebhooksServer.tls.selfSignedCert }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kargo-external-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.externalWebhooksServer.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ quote .Values.externalWebhooksServer.host }}
  issuerRef:
    kind: Issuer
    name: kargo-selfsigned-cert-issuer
  secretName: kargo-external-webhooks-server
{{- end }}
