{{- if .Values.externalWebhooksServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-external-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.externalWebhooksServer.labels" . | nindent 4 }}
data:
  KARGO_NAMESPACE: {{ .Release.Namespace }}
  LOG_LEVEL: {{ quote .Values.externalWebhooksServer.logLevel }}
  {{- if .Values.kubeconfigSecrets.kargo }}
  KUBECONFIG: /etc/kargo/kubeconfig.yaml
  {{- end }}
  {{- if .Values.externalWebhooksServer.tls.enabled }}
  TLS_ENABLED: "true"
  TLS_CERT_PATH: /etc/kargo/tls.crt
  TLS_KEY_PATH: /etc/kargo/tls.key
  {{- end }}
{{- end }}
