# Documentation: https://github.com/BirthdayResearch/oss-governance-bot
name: Governance

on:
  pull_request_target:
    types: [ synchronize, opened, labeled, unlabeled ]
  issues:
    types: [ opened, labeled, unlabeled ]
  issue_comment:
    types: [ created ]

jobs:
  governance:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    name: Governance
    runs-on: ubuntu-latest
    steps:
    - uses: BirthdayResearch/oss-governance-bot@3abd2d1fd2376ba9990fbc795e7a4c54254e9c61 # v4.0.0
      with:
        config-path: .github/governance.yml
