# Documentation: https://github.com/BirthdayResearch/oss-governance-bot
name: Governance

on:
  pull_request_target:
    types: [ synchronize, opened, labeled, unlabeled ]
  issues:
    types: [ opened, labeled, unlabeled ]
  issue_comment:
    types: [ created ]

permissions:
  contents: read

jobs:
  governance:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    name: Governance
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - uses: BirthdayResearch/oss-governance-bot@3abd2d1fd2376ba9990fbc795e7a4c54254e9c61 # v4.0.0
      with:
        config-path: .github/governance.yml
