name: 'Close Stale Issues'
on:
  schedule:
    - cron: '32 11 * * 1-5'  # 11:32 UTC / 07:32 EDT / 06:32 EST from Mon-Fri.

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Don't wait 6 hours to cancel workflow if it hangs.
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-label: 'stale'
          stale-issue-message: |
            This issue has been automatically marked as stale because it had no activity for 90 days. It will be closed if no activity occurs in the next 30 days but can be reopened if it becomes relevant again.
          days-before-stale: -1  # Don't stale PRs.
          days-before-issue-stale: 90
          days-before-issue-close: 30
          exempt-issue-labels: 'priority/normal,priority/high,priority/urgent'  # Only stale wontfix or low priority issues.